(@SiteID, @Lang, @Device, 'group_100', 1, 'Boathouse (Peterborough)', 'Boathouse (Peterborough)', 'Boathouse (Peterborough)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 2, 'Drum & Monkey (Dorridge)', 'Drum & Monkey (Dorridge)', 'Drum & Monkey (Dorridge)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 3, 'Rising Sun Inn (Wistaston)', 'Rising Sun Inn (Wistaston)', 'Rising Sun Inn (Wistaston)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 4, 'Abbey Fields (Kenilworth)', 'Abbey Fields (Kenilworth)', 'Abbey Fields (Kenilworth)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 5, 'Dog House (Frilford Heath)', 'Dog House (Frilford Heath)', 'Dog House (Frilford Heath)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 6, 'White Hart (Chalfont St Giles)', 'White Hart (Chalfont St Giles)', 'White Hart (Chalfont St Giles)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 7, 'Halfway House (Baildon)', 'Halfway House (Baildon)', 'Halfway House (Baildon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 8, 'Greaves Park (Lancaster)', 'Greaves Park (Lancaster)', 'Greaves Park (Lancaster)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 9, 'Keys (Slyne)', 'Keys (Slyne)', 'Keys (Slyne)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 10, 'Ashlea (Cheadle)', 'Ashlea (Cheadle)', 'Ashlea (Cheadle)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 11, 'Axe & Cleaver (Dunham Massey)', 'Axe & Cleaver (Dunham Massey)', 'Axe & Cleaver (Dunham Massey)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 12, 'Bakers Arms (Sewardstone)', 'Bakers Arms (Sewardstone)', 'Bakers Arms (Sewardstone)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 13, 'Barley Mow (Clifton Hampden)', 'Barley Mow (Clifton Hampden)', 'Barley Mow (Clifton Hampden)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 14, 'Battle Axes (Elstree)', 'Battle Axes (Elstree)', 'Battle Axes (Elstree)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 15, 'Bear & Staff (Gateacre)', 'Bear & Staff (Gateacre)', 'Bear & Staff (Gateacre)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 16, 'Bear Inn (Berkswell)', 'Bear Inn (Berkswell)', 'Bear Inn (Berkswell)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 17, 'Berkshire Arms (Midgham)', 'Berkshire Arms (Midgham)', 'Berkshire Arms (Midgham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 18, 'Blacksmiths Arms (Macclesfield)', 'Blacksmiths Arms (Macclesfield)', 'Blacksmiths Arms (Macclesfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 19, 'Blue Cap (Sandiway)', 'Blue Cap (Sandiway)', 'Blue Cap (Sandiway)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 20, 'Blundell Arms (Horwich)', 'Blundell Arms (Horwich)', 'Blundell Arms (Horwich)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 21, 'Boars Head (Herongate)', 'Boars Head (Herongate)', 'Boars Head (Herongate)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 22, 'Boat Inn (Catherine-De-Barnes)', 'Boat Inn (Catherine-De-Barnes)', 'Boat Inn (Catherine-De-Barnes)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 23, 'Boot & Slipper (Amersham)', 'Boot & Slipper (Amersham)', 'Boot & Slipper (Amersham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 24, 'Bottle & Glass Inn (Rainford)', 'Bottle & Glass Inn (Rainford)', 'Bottle & Glass Inn (Rainford)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 25, 'Bridge (Waterbeach)', 'Bridge (Waterbeach)', 'Bridge (Waterbeach)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 26, 'Bridge (Shawford)', 'Bridge (Shawford)', 'Bridge (Shawford)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 27, 'Britannia (Northampton)', 'Britannia (Northampton)', 'Britannia (Northampton)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 28, 'Bull (Goring-By-Sea)', 'Bull (Goring-By-Sea)', 'Bull (Goring-By-Sea)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 29, 'Bulls Head (Wilmslow)', 'Bulls Head (Wilmslow)', 'Bulls Head (Wilmslow)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 30, 'Bulls Head (Chiswick)', 'Bulls Head (Chiswick)', 'Bulls Head (Chiswick)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 31, 'Butley Ash (Butley)', 'Butley Ash (Butley)', 'Butley Ash (Butley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 32, 'Castle Hotel (Kirby Muxloe)', 'Castle Hotel (Kirby Muxloe)', 'Castle Hotel (Kirby Muxloe)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 33, 'Chequers Inn (Redbourn)', 'Chequers Inn (Redbourn)', 'Chequers Inn (Redbourn)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 34, 'Chiltern Hundreds (Maidstone)', 'Chiltern Hundreds (Maidstone)', 'Chiltern Hundreds (Maidstone)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 35, 'Cold Harbour (Blunsdon)', 'Cold Harbour (Blunsdon)', 'Cold Harbour (Blunsdon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 36, 'Cross Keys (Upsall)', 'Cross Keys (Upsall)', 'Cross Keys (Upsall)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 37, 'Crossroads (Weedon)', 'Crossroads (Weedon)', 'Crossroads (Weedon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 38, 'Crown Inn (Penn)', 'Crown Inn (Penn)', 'Crown Inn (Penn)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 39, 'Crown Inn (Eaton Socon)', 'Crown Inn (Eaton Socon)', 'Crown Inn (Eaton Socon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 40, 'De Trafford Arms (Alderley Edge)', 'De Trafford Arms (Alderley Edge)', 'De Trafford Arms (Alderley Edge)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 41, 'Didsbury (Didsbury)', 'Didsbury (Didsbury)', 'Didsbury (Didsbury)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 42, 'Dog & Partridge (Tutbury)', 'Dog & Partridge (Tutbury)', 'Dog & Partridge (Tutbury)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 43, 'Ethorpe Hotel (Gerrards Cross)', 'Ethorpe Hotel (Gerrards Cross)', 'Ethorpe Hotel (Gerrards Cross)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 44, 'Fairmile (Fairmile)', 'Fairmile (Fairmile)', 'Fairmile (Fairmile)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 45, 'Feathers (Burnham)', 'Feathers (Burnham)', 'Feathers (Burnham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 46, 'Ferry Inn (Wilford)', 'Ferry Inn (Wilford)', 'Ferry Inn (Wilford)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 47, 'Five Horseshoes (Little Berkhamsted', 'Five Horseshoes (Little Berkhamsted', 'Five Horseshoes (Little Berkhamsted', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 48, 'Four Oaks (Sutton Coldfield)', 'Four Oaks (Sutton Coldfield)', 'Four Oaks (Sutton Coldfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 49, 'Fox & Hounds (Longthorpe)', 'Fox & Hounds (Longthorpe)', 'Fox & Hounds (Longthorpe)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 50, 'Fox & Hounds (Bursledon)', 'Fox & Hounds (Bursledon)', 'Fox & Hounds (Bursledon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 51, 'Fox Inn (Bransford)', 'Fox Inn (Bransford)', 'Fox Inn (Bransford)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 52, 'Garden House (Edgbaston)', 'Garden House (Edgbaston)', 'Garden House (Edgbaston)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 53, 'Gatwick Manor (Lowfield Heath)', 'Gatwick Manor (Lowfield Heath)', 'Gatwick Manor (Lowfield Heath)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 54, 'George (Earley)', 'George (Earley)', 'George (Earley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 55, 'George Inn (Bathampton)', 'George Inn (Bathampton)', 'George Inn (Bathampton)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 56, 'Grange (Boreham)', 'Grange (Boreham)', 'Grange (Boreham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 57, 'Grapes Hotel (Wrea Green)', 'Grapes Hotel (Wrea Green)', 'Grapes Hotel (Wrea Green)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 58, 'Green Man (Harlow)', 'Green Man (Harlow)', 'Green Man (Harlow)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 59, 'Green Man (Great Offley)', 'Green Man (Great Offley)', 'Green Man (Great Offley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 60, 'Green Man Inn (Brackley Hatch)', 'Green Man Inn (Brackley Hatch)', 'Green Man Inn (Brackley Hatch)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 61, 'Greswolde Arms (Knowle)', 'Greswolde Arms (Knowle)', 'Greswolde Arms (Knowle)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 62, 'Greyhound (Milton Malsor)', 'Greyhound (Milton Malsor)', 'Greyhound (Milton Malsor)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 63, 'Griffin (Caversham)', 'Griffin (Caversham)', 'Griffin (Caversham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 64, 'Griffin (Bowdon)', 'Griffin (Bowdon)', 'Griffin (Bowdon)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 65, 'Hare & Hounds Inn (Hyde)', 'Hare & Hounds Inn (Hyde)', 'Hare & Hounds Inn (Hyde)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 66, 'Hatch (Old Basing)', 'Hatch (Old Basing)', 'Hatch (Old Basing)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 67, 'Himley House (Himley)', 'Himley House (Himley)', 'Himley House (Himley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 68, 'Hinderton Arms (Neston)', 'Hinderton Arms (Neston)', 'Hinderton Arms (Neston)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 69, 'Holly Bush (Lichfield)', 'Holly Bush (Lichfield)', 'Holly Bush (Lichfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 70, 'Horse & Groom (Writtle)', 'Horse & Groom (Writtle)', 'Horse & Groom (Writtle)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 71, 'Hutt (Ravenshead)', 'Hutt (Ravenshead)', 'Hutt (Ravenshead)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 72, 'Kilton Inn (Hoo Green)', 'Kilton Inn (Hoo Green)', 'Kilton Inn (Hoo Green)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 73, 'Kings Arms (Sandford-On-Thames)', 'Kings Arms (Sandford-On-Thames)', 'Kings Arms (Sandford-On-Thames)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 74, 'Kings Head (Masham)', 'Kings Head (Masham)', 'Kings Head (Masham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 75, 'Maenllwyd Inn (Rudry)', 'Maenllwyd Inn (Rudry)', 'Maenllwyd Inn (Rudry)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 76, 'Malthouse Farm (Whittle-Le-Woods)', 'Malthouse Farm (Whittle-Le-Woods)', 'Malthouse Farm (Whittle-Le-Woods)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 77, 'Mare & Colt (Summerfield)', 'Mare & Colt (Summerfield)', 'Mare & Colt (Summerfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 78, 'Mundy Arms (Mackworth)', 'Mundy Arms (Mackworth)', 'Mundy Arms (Mackworth)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 79, 'Nags Head (Burntwood)', 'Nags Head (Burntwood)', 'Nags Head (Burntwood)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 80, 'Old Bell (Harpenden)', 'Old Bell (Harpenden)', 'Old Bell (Harpenden)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 81, 'Old Bell (Grazeley Green)', 'Old Bell (Grazeley Green)', 'Old Bell (Grazeley Green)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 82, 'Old Bell (Oxted)', 'Old Bell (Oxted)', 'Old Bell (Oxted)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 83, 'Old Mill (Baginton)', 'Old Mill (Baginton)', 'Old Mill (Baginton)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 84, 'Old Mill (Brighouse)', 'Old Mill (Brighouse)', 'Old Mill (Brighouse)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 85, 'Peacock (Owler Bar)', 'Peacock (Owler Bar)', 'Peacock (Owler Bar)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 86, 'Peacock Inn (Forhill)', 'Peacock Inn (Forhill)', 'Peacock Inn (Forhill)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 87, 'Prince of Wales (Esher)', 'Prince of Wales (Esher)', 'Prince of Wales (Esher)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 88, 'Ravensworth Arms (Lamesley)', 'Ravensworth Arms (Lamesley)', 'Ravensworth Arms (Lamesley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 89, 'Red Lion (Martlesham)', 'Red Lion (Martlesham)', 'Red Lion (Martlesham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 90, 'Red Lion (Iver)', 'Red Lion (Iver)', 'Red Lion (Iver)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 91, 'Ring O’ Bells (Daresbury)', 'Ring O’ Bells (Daresbury)', 'Ring O’ Bells (Daresbury)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 92, 'Robin Hood (Shripney)', 'Robin Hood (Shripney)', 'Robin Hood (Shripney)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 93, 'Roebuck (Bilsborrow)', 'Roebuck (Bilsborrow)', 'Roebuck (Bilsborrow)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 94, 'Romper (Ringway)', 'Romper (Ringway)', 'Romper (Ringway)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 95, 'Rose & Crown (Wick)', 'Rose & Crown (Wick)', 'Rose & Crown (Wick)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 96, 'Royal Oak (Farnham Common)', 'Royal Oak (Farnham Common)', 'Royal Oak (Farnham Common)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 97, 'Running Horse Inn (Bewdley)', 'Running Horse Inn (Bewdley)', 'Running Horse Inn (Bewdley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 98, 'Rushcutters Arms (Thorpe St Andrew)', 'Rushcutters Arms (Thorpe St Andrew)', 'Rushcutters Arms (Thorpe St Andrew)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 99, 'Shepherds House (Warfield)', 'Shepherds House (Warfield)', 'Shepherds House (Warfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 100, 'Ship Inn (Alveston)', 'Ship Inn (Alveston)', 'Ship Inn (Alveston)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 101, 'Shipley Bridge (Burstow)', 'Shipley Bridge (Burstow)', 'Shipley Bridge (Burstow)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 102, 'Shire Horse (Littlewick Green)', 'Shire Horse (Littlewick Green)', 'Shire Horse (Littlewick Green)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 103, 'Shire Horse (Stafford)', 'Shire Horse (Stafford)', 'Shire Horse (Stafford)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 104, 'Shoulder of Mutton (Wendover)', 'Shoulder of Mutton (Wendover)', 'Shoulder of Mutton (Wendover)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 105, 'Smiths Arms (Beckwithshaw)', 'Smiths Arms (Beckwithshaw)', 'Smiths Arms (Beckwithshaw)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 106, 'Spencer Arms (Chapel Brampton)', 'Spencer Arms (Chapel Brampton)', 'Spencer Arms (Chapel Brampton)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 107, 'Stanley Gate (Bickerstaffe)', 'Stanley Gate (Bickerstaffe)', 'Stanley Gate (Bickerstaffe)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 108, 'Star Inn (Felbridge)', 'Star Inn (Felbridge)', 'Star Inn (Felbridge)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 109, 'Swan (Ash Vale)', 'Swan (Ash Vale)', 'Swan (Ash Vale)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 110, 'Swan (Winwick)', 'Swan (Winwick)', 'Swan (Winwick)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 111, 'Swan & Bottle (Uxbridge)', 'Swan & Bottle (Uxbridge)', 'Swan & Bottle (Uxbridge)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 112, 'Three Horse Shoes (Spellbrook)', 'Three Horse Shoes (Spellbrook)', 'Three Horse Shoes (Spellbrook)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 113, 'Tigers Head (Chislehurst)', 'Tigers Head (Chislehurst)', 'Tigers Head (Chislehurst)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 114, 'Travellers Rest (Mapperley)', 'Travellers Rest (Mapperley)', 'Travellers Rest (Mapperley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 115, 'Two Brewers (Chipperfield)', 'Two Brewers (Chipperfield)', 'Two Brewers (Chipperfield)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 116, 'Vauxhall Inn (Tonbridge)', 'Vauxhall Inn (Tonbridge)', 'Vauxhall Inn (Tonbridge)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 117, 'Wateringbury (Wateringbury)', 'Wateringbury (Wateringbury)', 'Wateringbury (Wateringbury)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 118, 'Watermill Inn (Dorking)', 'Watermill Inn (Dorking)', 'Watermill Inn (Dorking)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 119, 'Waterwitch (Odiham)', 'Waterwitch (Odiham)', 'Waterwitch (Odiham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 120, 'Wellington Hotel (Riding Mill)', 'Wellington Hotel (Riding Mill)', 'Wellington Hotel (Riding Mill)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 121, 'Wheatsheaf Hotel (Virginia Water)', 'Wheatsheaf Hotel (Virginia Water)', 'Wheatsheaf Hotel (Virginia Water)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 122, 'Wheatsheaf (North Waltham)', 'Wheatsheaf (North Waltham)', 'Wheatsheaf (North Waltham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 123, 'Wheatsheaf (Burton Joyce)', 'Wheatsheaf (Burton Joyce)', 'Wheatsheaf (Burton Joyce)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 124, 'Wheatstone Inn (Gloucester)', 'Wheatstone Inn (Gloucester)', 'Wheatstone Inn (Gloucester)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 125, 'White Horse (Shere)', 'White Horse (Shere)', 'White Horse (Shere)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 126, 'White House (Roundhay)', 'White House (Roundhay)', 'White House (Roundhay)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 127, 'White Rabbit (Lyndhurst)', 'White Rabbit (Lyndhurst)', 'White Rabbit (Lyndhurst)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 128, 'Woodman (Blackpill)', 'Woodman (Blackpill)', 'Woodman (Blackpill)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 129, 'Ye Olde Leathern Bottel (Barkham)', 'Ye Olde Leathern Bottel (Barkham)', 'Ye Olde Leathern Bottel (Barkham)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 130, 'Ye Olde Swan (Woughton-On-The-Green', 'Ye Olde Swan (Woughton-On-The-Green', 'Ye Olde Swan (Woughton-On-The-Green', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 131, 'Ye Olde Windsor Castle (Little Book', 'Ye Olde Windsor Castle (Little Book', 'Ye Olde Windsor Castle (Little Book', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 132, 'Yew Tree (Great Horkesley)', 'Yew Tree (Great Horkesley)', 'Yew Tree (Great Horkesley)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 133, 'Yews (Great Glen)', 'Yews (Great Glen)', 'Yews (Great Glen)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 134, 'Cross Keys (Norton Fitzwarren)', 'Cross Keys (Norton Fitzwarren)', 'Cross Keys (Norton Fitzwarren)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 135, 'Griffin (Bold Heath)', 'Griffin (Bold Heath)', 'Griffin (Bold Heath)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 136, 'Homestead (Bracebridge Heath)', 'Homestead (Bracebridge Heath)', 'Homestead (Bracebridge Heath)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 137, 'Riverside Hotel (Branston)', 'Riverside Hotel (Branston)', 'Riverside Hotel (Branston)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 138, 'Thornton Lodge (Little Thornton)', 'Thornton Lodge (Little Thornton)', 'Thornton Lodge (Little Thornton)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 139, 'Air Balloon (Birdlip)', 'Air Balloon (Birdlip)', 'Air Balloon (Birdlip)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 140, 'Fox & Hounds (Wimborne)', 'Fox & Hounds (Wimborne)', 'Fox & Hounds (Wimborne)', NULL, 'chefandbrewer-', NULL),
(@SiteID, @Lang, @Device, 'group_100', 141, 'Queens Head (Burley)', 'Queens Head (Burley)', 'Queens Head (Burley)', NULL, 'chefandbrewer-', NULL),
