(@SiteID, @Lang, @Device, 'group_100', 1, '2nd Module and refactor', '2nd Module and refactor', '2nd Module and refactor', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 2, 'Flyer, Chelmsford', 'Flyer, Chelmsford', 'Flyer, Chelmsford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 3, 'Harrier, Peterborough', 'Harrier, Peterborough', 'Harrier, Peterborough', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 4, 'Jolly Scotchman (Sleaford)', 'Jolly Scotchman (Sleaford)', 'Jolly Scotchman (Sleaford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 5, 'Romans Rest (Worksop)', 'Romans Rest (Worksop)', 'Romans Rest (Worksop)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 6, 'Boundary House (Abingdon)', 'Boundary House (Abingdon)', 'Boundary House (Abingdon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 7, 'Hayride, Beverley', 'Hayride, Beverley', 'Hayride, Beverley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 8, 'Hop House, Tunbridge Wells', 'Hop House, Tunbridge Wells', 'Hop House, Tunbridge Wells', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 9, 'Mill House (Broughton)', 'Mill House (Broughton)', 'Mill House (Broughton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 10, 'Punch & Judy, Grafton Way Ipswich', 'Punch & Judy, Grafton Way Ipswich', 'Punch & Judy, Grafton Way Ipswich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 11, 'Sailmakers, Hull', 'Sailmakers, Hull', 'Sailmakers, Hull', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 12, 'Air Balloon (Filton)', 'Air Balloon (Filton)', 'Air Balloon (Filton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 13, 'Albion, Rainham', 'Albion, Rainham', 'Albion, Rainham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 14, 'Amington, Tamworth', 'Amington, Tamworth', 'Amington, Tamworth', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 15, 'Angel Inn (Rothwell)', 'Angel Inn (Rothwell)', 'Angel Inn (Rothwell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 16, 'Bay Horse (Ashton-In-Makerfield)', 'Bay Horse (Ashton-In-Makerfield)', 'Bay Horse (Ashton-In-Makerfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 17, 'Belfry (Beighton)', 'Belfry (Beighton)', 'Belfry (Beighton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 18, 'Birch Tree, Birkenhead', 'Birch Tree, Birkenhead', 'Birch Tree, Birkenhead', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 19, 'Blue Bell (Attenborough)', 'Blue Bell (Attenborough)', 'Blue Bell (Attenborough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 20, 'Bowman (Hucknall)', 'Bowman (Hucknall)', 'Bowman (Hucknall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 21, 'Brentwood Hotel, Rotherham', 'Brentwood Hotel, Rotherham', 'Brentwood Hotel, Rotherham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 22, 'Bridge Inn, Port Sunlight', 'Bridge Inn, Port Sunlight', 'Bridge Inn, Port Sunlight', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 23, 'Bridgewater Arms, Leeds', 'Bridgewater Arms, Leeds', 'Bridgewater Arms, Leeds', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 24, 'Brinkburn (Darlington)', 'Brinkburn (Darlington)', 'Brinkburn (Darlington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 25, 'Bull (Horns Cross)', 'Bull (Horns Cross)', 'Bull (Horns Cross)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 26, 'Bullock Smithy (Hazel Grove)', 'Bullock Smithy (Hazel Grove)', 'Bullock Smithy (Hazel Grove)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 27, 'Butchers Arms, Great Sankey', 'Butchers Arms, Great Sankey', 'Butchers Arms, Great Sankey', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 28, 'Cardiff Bay Tavern (Cardiff)', 'Cardiff Bay Tavern (Cardiff)', 'Cardiff Bay Tavern (Cardiff)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 29, 'Carousel (Reddish)', 'Carousel (Reddish)', 'Carousel (Reddish)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 30, 'Carr Mill, St. Helens', 'Carr Mill, St. Helens', 'Carr Mill, St. Helens', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 31, 'Castle, Bristol', 'Castle, Bristol', 'Castle, Bristol', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 32, 'Castle Hotel, Droitwich', 'Castle Hotel, Droitwich', 'Castle Hotel, Droitwich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 33, 'Cat & Lion (Stretton)', 'Cat & Lion (Stretton)', 'Cat & Lion (Stretton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 34, 'Chambers', 'Chambers', 'Chambers', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 35, 'Chase Hotel', 'Chase Hotel', 'Chase Hotel', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 36, 'Coach & Horses, Portsmouth', 'Coach & Horses, Portsmouth', 'Coach & Horses, Portsmouth', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 37, 'Cock Hotel, Worsley', 'Cock Hotel, Worsley', 'Cock Hotel, Worsley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 38, 'Cocked Hat, Gosport', 'Cocked Hat, Gosport', 'Cocked Hat, Gosport', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 39, 'Corn Exchange, Brierley Hill', 'Corn Exchange, Brierley Hill', 'Corn Exchange, Brierley Hill', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 40, 'Corner House (Branston)', 'Corner House (Branston)', 'Corner House (Branston)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 41, 'Corner House Hotel (Newcastle-Upon-Tyne)', 'Corner House Hotel (Newcastle-Upon-Tyne)', 'Corner House Hotel (Newcastle-Upon-Tyne)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 42, 'Coventry Oak (Wyken)', 'Coventry Oak (Wyken)', 'Coventry Oak (Wyken)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 43, 'Cross, Kingswinford', 'Cross, Kingswinford', 'Cross, Kingswinford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 44, 'Donkey Derby, Chesterfield', 'Donkey Derby, Chesterfield', 'Donkey Derby, Chesterfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 45, 'Downham Arms (Wickford)', 'Downham Arms (Wickford)', 'Downham Arms (Wickford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 46, 'Drawbridge Inn (Shirley)', 'Drawbridge Inn (Shirley)', 'Drawbridge Inn (Shirley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 47, 'Duke of Wellington, Kenton', 'Duke of Wellington, Kenton', 'Duke of Wellington, Kenton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 48, 'Fair Maid, Cottingham', 'Fair Maid, Cottingham', 'Fair Maid, Cottingham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 49, 'Five Bells, Finchley', 'Five Bells, Finchley', 'Five Bells, Finchley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 50, 'Fountain, South Shields', 'Fountain, South Shields', 'Fountain, South Shields', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 51, 'Fox & Crown, Sutton-in-Ashfield', 'Fox & Crown, Sutton-in-Ashfield', 'Fox & Crown, Sutton-in-Ashfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 52, 'Fox & Hounds, Newcastle upon Tyne', 'Fox & Hounds, Newcastle upon Tyne', 'Fox & Hounds, Newcastle upon Tyne', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 53, 'Fox Hunters, North Shields', 'Fox Hunters, North Shields', 'Fox Hunters, North Shields', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 54, 'Friar Tuck', 'Friar Tuck', 'Friar Tuck', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 55, 'Glasshouse, Wath-upon-Dearne', 'Glasshouse, Wath-upon-Dearne', 'Glasshouse, Wath-upon-Dearne', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 56, 'Golden Eagle, Thornton Cleveleys', 'Golden Eagle, Thornton Cleveleys', 'Golden Eagle, Thornton Cleveleys', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 57, 'Good Intent, Hornchurch', 'Good Intent, Hornchurch', 'Good Intent, Hornchurch', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 58, 'Gosling Bridge Inn, Carlisle', 'Gosling Bridge Inn, Carlisle', 'Gosling Bridge Inn, Carlisle', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 59, 'Grace Arms', 'Grace Arms', 'Grace Arms', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 60, 'Hare & Hounds (Tarbock)', 'Hare & Hounds (Tarbock)', 'Hare & Hounds (Tarbock)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 61, 'Hill Top, Stanley', 'Hill Top, Stanley', 'Hill Top, Stanley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 62, 'Hinckley Knight, Hinckley', 'Hinckley Knight, Hinckley', 'Hinckley Knight, Hinckley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 63, 'Jolly Miller (West Derby)', 'Jolly Miller (West Derby)', 'Jolly Miller (West Derby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 64, 'Lamb Inn (Rustington)', 'Lamb Inn (Rustington)', 'Lamb Inn (Rustington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 65, 'Local Hero, Leicester', 'Local Hero, Leicester', 'Local Hero, Leicester', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 66, 'Lodge, Alvaston', 'Lodge, Alvaston', 'Lodge, Alvaston', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 67, 'Lord Derby, Lytham St. Annes', 'Lord Derby, Lytham St. Annes', 'Lord Derby, Lytham St. Annes', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 68, 'Lumbertubs, Boothville', 'Lumbertubs, Boothville', 'Lumbertubs, Boothville', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 69, 'Lupset Hotel, Wakefield', 'Lupset Hotel, Wakefield', 'Lupset Hotel, Wakefield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 70, 'Lutley Oak, Halesowen', 'Lutley Oak, Halesowen', 'Lutley Oak, Halesowen', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 71, 'Man of Gwent, Newport', 'Man of Gwent, Newport', 'Man of Gwent, Newport', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 72, 'Mulberry (Goring-By-Sea)', 'Mulberry (Goring-By-Sea)', 'Mulberry (Goring-By-Sea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 73, 'Nags Head (Mickleover)', 'Nags Head (Mickleover)', 'Nags Head (Mickleover)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 74, 'Narborough Arms (Narborough)', 'Narborough Arms (Narborough)', 'Narborough Arms (Narborough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 75, 'Nelson Hotel, Wallasey', 'Nelson Hotel, Wallasey', 'Nelson Hotel, Wallasey', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 76, 'Norman Conquest, Middlesbrough', 'Norman Conquest, Middlesbrough', 'Norman Conquest, Middlesbrough', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 77, 'Nosey Parker, Lincoln', 'Nosey Parker, Lincoln', 'Nosey Parker, Lincoln', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 78, 'Number 3, Blackpool', 'Number 3, Blackpool', 'Number 3, Blackpool', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 79, 'Old Ash Tree, Chatham', 'Old Ash Tree, Chatham', 'Old Ash Tree, Chatham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 80, 'Old Grey Mare, Hull', 'Old Grey Mare, Hull', 'Old Grey Mare, Hull', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 81, 'Old Leyland Gates, Leyland', 'Old Leyland Gates, Leyland', 'Old Leyland Gates, Leyland', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 82, 'Old Walnut Tree, Southend-on-Sea', 'Old Walnut Tree, Southend-on-Sea', 'Old Walnut Tree, Southend-on-Sea', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 83, 'Pack Horse (Burnopfield)', 'Pack Horse (Burnopfield)', 'Pack Horse (Burnopfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 84, 'Parc-Y-Prior Inn (Malpas)', 'Parc-Y-Prior Inn (Malpas)', 'Parc-Y-Prior Inn (Malpas)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 85, 'Peacock Hotel (Chester)', 'Peacock Hotel (Chester)', 'Peacock Hotel (Chester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 86, 'Pelican (West Timperley)', 'Pelican (West Timperley)', 'Pelican (West Timperley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 87, 'Plough (Houghton Green)', 'Plough (Houghton Green)', 'Plough (Houghton Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 88, 'Polite Vicar (Basford)', 'Polite Vicar (Basford)', 'Polite Vicar (Basford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 89, 'Prince of Wales, Fleet', 'Prince of Wales, Fleet', 'Prince of Wales, Fleet', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 90, 'Prince of Wales, Jarrow', 'Prince of Wales, Jarrow', 'Prince of Wales, Jarrow', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 91, 'Priorslee (Priorslee)', 'Priorslee (Priorslee)', 'Priorslee (Priorslee)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 92, 'Quakerwood, Acomb', 'Quakerwood, Acomb', 'Quakerwood, Acomb', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 93, 'Queen B, Chelmsford', 'Queen B, Chelmsford', 'Queen B, Chelmsford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 94, 'Railway Hotel, Greenford', 'Railway Hotel, Greenford', 'Railway Hotel, Greenford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 95, 'Ridgeway Arms (Mosborough)', 'Ridgeway Arms (Mosborough)', 'Ridgeway Arms (Mosborough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 96, 'Robin Hood (Clifton)', 'Robin Hood (Clifton)', 'Robin Hood (Clifton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 97, 'Rodmill, Eastbourne', 'Rodmill, Eastbourne', 'Rodmill, Eastbourne', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 98, 'Rope Walk, Huddersfield', 'Rope Walk, Huddersfield', 'Rope Walk, Huddersfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 99, 'Rose & Crown (Lenton)', 'Rose & Crown (Lenton)', 'Rose & Crown (Lenton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 100, 'Roundel (Thornaby)', 'Roundel (Thornaby)', 'Roundel (Thornaby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 101, 'Rovers Tye, Colchester', 'Rovers Tye, Colchester', 'Rovers Tye, Colchester', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 102, 'Royal George , Ipswich', 'Royal George , Ipswich', 'Royal George , Ipswich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 103, 'Seven Stars Inn (Eccleston)', 'Seven Stars Inn (Eccleston)', 'Seven Stars Inn (Eccleston)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 104, 'Sherwin Arms (Bramcote)', 'Sherwin Arms (Bramcote)', 'Sherwin Arms (Bramcote)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 105, 'Shovels (Marton Moss)', 'Shovels (Marton Moss)', 'Shovels (Marton Moss)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 106, 'Singing Chocker (Glasshoughton)', 'Singing Chocker (Glasshoughton)', 'Singing Chocker (Glasshoughton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 107, 'Sir John Brunner, Northwich', 'Sir John Brunner, Northwich', 'Sir John Brunner, Northwich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 108, 'Southern Cross, Middlesbrough', 'Southern Cross, Middlesbrough', 'Southern Cross, Middlesbrough', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 109, 'Southern Cross, Watford', 'Southern Cross, Watford', 'Southern Cross, Watford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 110, 'Summit Inn (Royton)', 'Summit Inn (Royton)', 'Summit Inn (Royton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 111, 'Surrey (St Johns)', 'Surrey (St Johns)', 'Surrey (St Johns)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 112, 'Sussex Barn, Horsham', 'Sussex Barn, Horsham', 'Sussex Barn, Horsham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 113, 'Swift Hound, Blackpool', 'Swift Hound, Blackpool', 'Swift Hound, Blackpool', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 114, 'Tamar, Crownhill', 'Tamar, Crownhill', 'Tamar, Crownhill', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 115, 'Tiger Moth, Chatham', 'Tiger Moth, Chatham', 'Tiger Moth, Chatham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 116, 'Torch, Wembley', 'Torch, Wembley', 'Torch, Wembley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 117, 'Travellers Rest, Hartlepool', 'Travellers Rest, Hartlepool', 'Travellers Rest, Hartlepool', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 118, 'Venture (Highfield)', 'Venture (Highfield)', 'Venture (Highfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 119, 'Village Green (Stockland Green)', 'Village Green (Stockland Green)', 'Village Green (Stockland Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 120, 'Waggon Team, Gateshead', 'Waggon Team, Gateshead', 'Waggon Team, Gateshead', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 121, 'Walter Tull (Sixfields)', 'Walter Tull (Sixfields)', 'Walter Tull (Sixfields)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 122, 'Warren Lodge, Scunthorpe', 'Warren Lodge, Scunthorpe', 'Warren Lodge, Scunthorpe', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 123, 'Water Tower (Tilehurst)', 'Water Tower (Tilehurst)', 'Water Tower (Tilehurst)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 124, 'Waterside Inn (Goodrington)', 'Waterside Inn (Goodrington)', 'Waterside Inn (Goodrington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 125, 'Wheatsheaf (Great Wyrley)', 'Wheatsheaf (Great Wyrley)', 'Wheatsheaf (Great Wyrley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 126, 'Whistling Goose (Sutton Fields)', 'Whistling Goose (Sutton Fields)', 'Whistling Goose (Sutton Fields)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 127, 'White Horse, Sutton Coldfield', 'White Horse, Sutton Coldfield', 'White Horse, Sutton Coldfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 128, 'Whitehills, Northampton', 'Whitehills, Northampton', 'Whitehills, Northampton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 129, 'Yacht, Bexleyheath', 'Yacht, Bexleyheath', 'Yacht, Bexleyheath', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 130, 'Yardley Arms (Stechford)', 'Yardley Arms (Stechford)', 'Yardley Arms (Stechford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 131, 'Yarrowbridge, Chorley', 'Yarrowbridge, Chorley', 'Yarrowbridge, Chorley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 132, 'Starting Gate, Nottingham', 'Starting Gate, Nottingham', 'Starting Gate, Nottingham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 133, 'Royal Sovereign (Salford)', 'Royal Sovereign (Salford)', 'Royal Sovereign (Salford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 134, 'Shuttle & Loom, Darlington', 'Shuttle & Loom, Darlington', 'Shuttle & Loom, Darlington', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 135, 'Wellington (Bury)', 'Wellington (Bury)', 'Wellington (Bury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 136, 'Feathers, Maidstone', 'Feathers, Maidstone', 'Feathers, Maidstone', NULL, 'belhaven', NULL),
