(@SiteID, @Lang, @Device, 'group_100', 1, 'Pied Calf (Spalding)', 'Pied Calf (Spalding)', 'Pied Calf (Spalding)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 2, 'Old Swan (Bletchley)', 'Old Swan (Bletchley)', 'Old Swan (Bletchley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 3, 'Crown (Luton)', 'Crown (Luton)', 'Crown (Luton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 4, 'Lansdown (Cheltenham)', 'Lansdown (Cheltenham)', 'Lansdown (Cheltenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 5, 'Farmers Arms (Stockport)', 'Farmers Arms (Stockport)', 'Farmers Arms (Stockport)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 6, 'Golden Hind (Stockport)', 'Golden Hind (Stockport)', 'Golden Hind (Stockport)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 7, 'Bollo House (Chiswick)', 'Bollo House (Chiswick)', 'Bollo House (Chiswick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 8, 'Bull (Braintree)', 'Bull (Braintree)', 'Bull (Braintree)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 9, 'Orange Tree (Braintree)', 'Orange Tree (Braintree)', 'Orange Tree (Braintree)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 10, 'Bushel (Bury St Edmunds)', 'Bushel (Bury St Edmunds)', 'Bushel (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 11, 'Dog & Partridge (Bury St Edmunds)', 'Dog & Partridge (Bury St Edmunds)', 'Dog & Partridge (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 12, 'Grapes (Bury St Edmunds)', 'Grapes (Bury St Edmunds)', 'Grapes (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 13, 'Macebearer (Bury St Edmunds)', 'Macebearer (Bury St Edmunds)', 'Macebearer (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 14, 'Spread Eagle (Bury St Edmunds)', 'Spread Eagle (Bury St Edmunds)', 'Spread Eagle (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 15, 'Tollgate (Bury St Edmunds)', 'Tollgate (Bury St Edmunds)', 'Tollgate (Bury St Edmunds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 16, 'Duke Of Cambridge (Cambridge)', 'Duke Of Cambridge (Cambridge)', 'Duke Of Cambridge (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 17, 'Fort St George (Cambridge)', 'Fort St George (Cambridge)', 'Fort St George (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 18, 'Granta (Cambridge)', 'Granta (Cambridge)', 'Granta (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 19, 'Green Dragon (Cambridge)', 'Green Dragon (Cambridge)', 'Green Dragon (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 20, 'Prince Regent (Cambridge)', 'Prince Regent (Cambridge)', 'Prince Regent (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 21, 'Rock (Cambridge)', 'Rock (Cambridge)', 'Rock (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 22, 'Bull (Newmarket)', 'Bull (Newmarket)', 'Bull (Newmarket)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 23, 'Oak (Stowmarket)', 'Oak (Stowmarket)', 'Oak (Stowmarket)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 24, 'Bull (East Dereham)', 'Bull (East Dereham)', 'Bull (East Dereham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 25, 'Sandmartin (Thurrock)', 'Sandmartin (Thurrock)', 'Sandmartin (Thurrock)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 26, 'Otter (Thorpe Marriott)', 'Otter (Thorpe Marriott)', 'Otter (Thorpe Marriott)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 27, 'Stag (Ascot)', 'Stag (Ascot)', 'Stag (Ascot)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 28, 'Old Punch Bowl (Crawley)', 'Old Punch Bowl (Crawley)', 'Old Punch Bowl (Crawley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 29, 'Inn On The Green (Stanford)', 'Inn On The Green (Stanford)', 'Inn On The Green (Stanford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 30, 'Archers (Romford)', 'Archers (Romford)', 'Archers (Romford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 31, 'Doctors Tonic (Welwyn Garden)', 'Doctors Tonic (Welwyn Garden)', 'Doctors Tonic (Welwyn Garden)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 32, 'Fig Tree (Uxbridge)', 'Fig Tree (Uxbridge)', 'Fig Tree (Uxbridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 33, 'Grove (Sean O'g) (Surbiton)', 'Grove (Sean O'g) (Surbiton)', 'Grove (Sean O'g) (Surbiton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 34, 'Cricketers (Richmond)', 'Cricketers (Richmond)', 'Cricketers (Richmond)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 35, 'Emporium (Fleet)', 'Emporium (Fleet)', 'Emporium (Fleet)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 36, 'Scholars Arms (Southampton)', 'Scholars Arms (Southampton)', 'Scholars Arms (Southampton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 37, 'Old Fields (Southfields)', 'Old Fields (Southfields)', 'Old Fields (Southfields)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 38, 'Station (Uckfield)', 'Station (Uckfield)', 'Station (Uckfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 39, 'Greyfisher, Salisbury', 'Greyfisher, Salisbury', 'Greyfisher, Salisbury', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 40, 'Magpie (Sunbury-On-Thames)', 'Magpie (Sunbury-On-Thames)', 'Magpie (Sunbury-On-Thames)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 41, 'Cricketers (Warfield)', 'Cricketers (Warfield)', 'Cricketers (Warfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 42, 'Allsop Arms (London)', 'Allsop Arms (London)', 'Allsop Arms (London)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 43, 'Bunch of Grapes (Brompton)', 'Bunch of Grapes (Brompton)', 'Bunch of Grapes (Brompton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 44, 'City Barge (Chiswick)', 'City Barge (Chiswick)', 'City Barge (Chiswick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 45, 'Kings Arms (Greenwich)', 'Kings Arms (Greenwich)', 'Kings Arms (Greenwich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 46, 'Ram (Kingston-Upon-Thames)', 'Ram (Kingston-Upon-Thames)', 'Ram (Kingston-Upon-Thames)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 47, 'Sawyers Arms (Paddington)', 'Sawyers Arms (Paddington)', 'Sawyers Arms (Paddington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 48, 'St Margarets (Twickenham)', 'St Margarets (Twickenham)', 'St Margarets (Twickenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 49, 'Riverside Farm, Skelton', 'Riverside Farm, Skelton', 'Riverside Farm, Skelton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 50, 'Masons Arms (Mayfair)', 'Masons Arms (Mayfair)', 'Masons Arms (Mayfair)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 51, 'Grove (Ealing)', 'Grove (Ealing)', 'Grove (Ealing)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 52, 'West Gate (Bath)', 'West Gate (Bath)', 'West Gate (Bath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 53, 'Greyhound (Finchampsted)', 'Greyhound (Finchampsted)', 'Greyhound (Finchampsted)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 54, 'Old School House (Mere Green)', 'Old School House (Mere Green)', 'Old School House (Mere Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 55, 'Cow (Poole)', 'Cow (Poole)', 'Cow (Poole)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 56, 'Cock & Pye (Ipswich)', 'Cock & Pye (Ipswich)', 'Cock & Pye (Ipswich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 57, 'Man On The Moon (Ipswich)', 'Man On The Moon (Ipswich)', 'Man On The Moon (Ipswich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 58, 'Cricketers (Rainham)', 'Cricketers (Rainham)', 'Cricketers (Rainham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 59, 'Isle of Ely (Ely)', 'Isle of Ely (Ely)', 'Isle of Ely (Ely)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 60, 'Tulse Hill Hotel (Tulse Hill)', 'Tulse Hill Hotel (Tulse Hill)', 'Tulse Hill Hotel (Tulse Hill)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 61, 'Bell (Bredhurst)', 'Bell (Bredhurst)', 'Bell (Bredhurst)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 62, 'Prince Of Wales (East Molesey)', 'Prince Of Wales (East Molesey)', 'Prince Of Wales (East Molesey)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 63, 'Gemini (Dereham)', 'Gemini (Dereham)', 'Gemini (Dereham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 64, 'Boathouse (Cambridge)', 'Boathouse (Cambridge)', 'Boathouse (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 65, 'Red Lion (Langley)', 'Red Lion (Langley)', 'Red Lion (Langley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 66, 'Red House (Croxley Green)', 'Red House (Croxley Green)', 'Red House (Croxley Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 67, 'Crown (Hazlemere)', 'Crown (Hazlemere)', 'Crown (Hazlemere)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 68, 'Willow (Harlow)', 'Willow (Harlow)', 'Willow (Harlow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 69, 'Eagle (Cambridge)', 'Eagle (Cambridge)', 'Eagle (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 70, 'Baron Of Beef (Cambridge)', 'Baron Of Beef (Cambridge)', 'Baron Of Beef (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 71, 'Owl & Pussycat (Felixstowe)', 'Owl & Pussycat (Felixstowe)', 'Owl & Pussycat (Felixstowe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 72, 'Old Rep (Ipswich)', 'Old Rep (Ipswich)', 'Old Rep (Ipswich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 73, 'Old Tea Warehouse (London Ec3)', 'Old Tea Warehouse (London Ec3)', 'Old Tea Warehouse (London Ec3)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 74, 'Finery (London W1)', 'Finery (London W1)', 'Finery (London W1)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 75, 'Cross Hands (Bristol)', 'Cross Hands (Bristol)', 'Cross Hands (Bristol)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 76, 'Shakespeare (Bristol)', 'Shakespeare (Bristol)', 'Shakespeare (Bristol)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 77, 'Star (Bristol)', 'Star (Bristol)', 'Star (Bristol)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 78, 'Cameo (Leith)', 'Cameo (Leith)', 'Cameo (Leith)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 79, 'Swan (Abbotts Langley)', 'Swan (Abbotts Langley)', 'Swan (Abbotts Langley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 80, 'Bull (Bedford)', 'Bull (Bedford)', 'Bull (Bedford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 81, 'Fox & Hounds (Bedford)', 'Fox & Hounds (Bedford)', 'Fox & Hounds (Bedford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 82, 'George & Dragon (Bedford)', 'George & Dragon (Bedford)', 'George & Dragon (Bedford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 83, 'Ship (Bedford)', 'Ship (Bedford)', 'Ship (Bedford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 84, 'White Hart (Biggleswade)', 'White Hart (Biggleswade)', 'White Hart (Biggleswade)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 85, 'Yorkshire Grey (Biggleswade)', 'Yorkshire Grey (Biggleswade)', 'Yorkshire Grey (Biggleswade)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 86, 'Fox & Hounds (Croxley Green)', 'Fox & Hounds (Croxley Green)', 'Fox & Hounds (Croxley Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 87, 'Red Lion (Grantchester)', 'Red Lion (Grantchester)', 'Red Lion (Grantchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 88, 'Duncombe Arms (Hertford)', 'Duncombe Arms (Hertford)', 'Duncombe Arms (Hertford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 89, 'Cock (Hitchin)', 'Cock (Hitchin)', 'Cock (Hitchin)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 90, 'Jolly Milliner (Luton)', 'Jolly Milliner (Luton)', 'Jolly Milliner (Luton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 91, 'Hansom Cab (Luton)', 'Hansom Cab (Luton)', 'Hansom Cab (Luton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 92, 'Jolly Topers (Luton)', 'Jolly Topers (Luton)', 'Jolly Topers (Luton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 93, 'Dolphin (Melbourn)', 'Dolphin (Melbourn)', 'Dolphin (Melbourn)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 94, 'Coach House (St Neots)', 'Coach House (St Neots)', 'Coach House (St Neots)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 95, 'Red Lion (Stevenage)', 'Red Lion (Stevenage)', 'Red Lion (Stevenage)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 96, 'Mulberry Tree (Stevenage)', 'Mulberry Tree (Stevenage)', 'Mulberry Tree (Stevenage)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 97, 'Punch House (Ware)', 'Punch House (Ware)', 'Punch House (Ware)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 98, 'Estcourt Tavern (Watford)', 'Estcourt Tavern (Watford)', 'Estcourt Tavern (Watford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 99, 'Kingfisher (Newport Pagnell)', 'Kingfisher (Newport Pagnell)', 'Kingfisher (Newport Pagnell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 100, 'Bumble Bee (Flitwick)', 'Bumble Bee (Flitwick)', 'Bumble Bee (Flitwick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 101, 'Golden Fleece (London Ec4)', 'Golden Fleece (London Ec4)', 'Golden Fleece (London Ec4)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 102, 'Hope & Anchor (Islington)', 'Hope & Anchor (Islington)', 'Hope & Anchor (Islington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 103, 'Beacon (Basingstoke)', 'Beacon (Basingstoke)', 'Beacon (Basingstoke)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 104, 'Harvest Moon (Bishops Stortford)', 'Harvest Moon (Bishops Stortford)', 'Harvest Moon (Bishops Stortford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 105, 'White Lion (Sawbridgeworth)', 'White Lion (Sawbridgeworth)', 'White Lion (Sawbridgeworth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 106, 'Dorset Arms (East Grinstead)', 'Dorset Arms (East Grinstead)', 'Dorset Arms (East Grinstead)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 107, 'Beechdale (Nottingham)', 'Beechdale (Nottingham)', 'Beechdale (Nottingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 108, 'Bell Inn (Nottingham)', 'Bell Inn (Nottingham)', 'Bell Inn (Nottingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 109, 'Broad Oak (Strelley Village)', 'Broad Oak (Strelley Village)', 'Broad Oak (Strelley Village)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 110, 'Counting House (Leicester)', 'Counting House (Leicester)', 'Counting House (Leicester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 111, 'Governors House (Cheadle Hulme)', 'Governors House (Cheadle Hulme)', 'Governors House (Cheadle Hulme)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 112, 'John Gilbert (Worsley)', 'John Gilbert (Worsley)', 'John Gilbert (Worsley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 113, 'Kings Ransom (Sale)', 'Kings Ransom (Sale)', 'Kings Ransom (Sale)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 114, 'Lady Bay (West Bridgford)', 'Lady Bay (West Bridgford)', 'Lady Bay (West Bridgford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 115, 'Lord Darcy (Leeds)', 'Lord Darcy (Leeds)', 'Lord Darcy (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 116, 'Meadow Covert (Edwalton)', 'Meadow Covert (Edwalton)', 'Meadow Covert (Edwalton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 117, 'Nabb Inn (Hucknall)', 'Nabb Inn (Hucknall)', 'Nabb Inn (Hucknall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 118, 'Crabmill (Oldswinford)', 'Crabmill (Oldswinford)', 'Crabmill (Oldswinford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 119, 'Peacock (Clifton)', 'Peacock (Clifton)', 'Peacock (Clifton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 120, 'Plainsman (Mapperley)', 'Plainsman (Mapperley)', 'Plainsman (Mapperley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 121, 'Sir John Warren (Ilkeston)', 'Sir John Warren (Ilkeston)', 'Sir John Warren (Ilkeston)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 122, 'Shepley Spitfire (Sheffield)', 'Shepley Spitfire (Sheffield)', 'Shepley Spitfire (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 123, 'Sun Inn (Eastwood)', 'Sun Inn (Eastwood)', 'Sun Inn (Eastwood)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 124, 'Test Match Hotel (W Bridgford)', 'Test Match Hotel (W Bridgford)', 'Test Match Hotel (W Bridgford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 125, 'Three Ponds (Nuthall)', 'Three Ponds (Nuthall)', 'Three Ponds (Nuthall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 126, 'Waterside Inn (Leigh)', 'Waterside Inn (Leigh)', 'Waterside Inn (Leigh)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 127, 'Ye Olde Trip Jerusalem (Nottingham)', 'Ye Olde Trip Jerusalem (Nottingham)', 'Ye Olde Trip Jerusalem (Nottingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 128, 'Inn On The Green (Harpenden)', 'Inn On The Green (Harpenden)', 'Inn On The Green (Harpenden)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 129, 'Pied Piper (Stevenage)', 'Pied Piper (Stevenage)', 'Pied Piper (Stevenage)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 130, 'Cricketers (Milton Keynes)', 'Cricketers (Milton Keynes)', 'Cricketers (Milton Keynes)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 131, 'Crab & Winkle (Peterborough)', 'Crab & Winkle (Peterborough)', 'Crab & Winkle (Peterborough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 132, 'Kensington (Milton Keynes)', 'Kensington (Milton Keynes)', 'Kensington (Milton Keynes)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 133, 'Tawny Owl, Walnut Tree', 'Tawny Owl, Walnut Tree', 'Tawny Owl, Walnut Tree', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 134, 'Acorn, Bicester', 'Acorn, Bicester', 'Acorn, Bicester', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 135, 'Bay Tree (Grove)', 'Bay Tree (Grove)', 'Bay Tree (Grove)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 136, 'Mill (Salisbury)', 'Mill (Salisbury)', 'Mill (Salisbury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 137, 'Black Horse (Kidlington)', 'Black Horse (Kidlington)', 'Black Horse (Kidlington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 138, 'Bowyer Arms (Radley)', 'Bowyer Arms (Radley)', 'Bowyer Arms (Radley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 139, 'Cricketers (Yateley)', 'Cricketers (Yateley)', 'Cricketers (Yateley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 140, 'Messenger (Swindon)', 'Messenger (Swindon)', 'Messenger (Swindon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 141, 'Lord Nelson, Wantage', 'Lord Nelson, Wantage', 'Lord Nelson, Wantage', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 142, 'Midget (Abingdon)', 'Midget (Abingdon)', 'Midget (Abingdon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 143, 'Glassworks (Cardiff)', 'Glassworks (Cardiff)', 'Glassworks (Cardiff)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 144, 'Old White Hart (Hook)', 'Old White Hart (Hook)', 'Old White Hart (Hook)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 145, 'Oak (Didcot)', 'Oak (Didcot)', 'Oak (Didcot)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 146, 'Royal Oak (Yateley)', 'Royal Oak (Yateley)', 'Royal Oak (Yateley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 147, 'Royal Standard (Camberley)', 'Royal Standard (Camberley)', 'Royal Standard (Camberley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 148, 'Silver Birch (Bracknell)', 'Silver Birch (Bracknell)', 'Silver Birch (Bracknell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 149, 'Sportsman (Reading)', 'Sportsman (Reading)', 'Sportsman (Reading)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 150, 'Swan (Pangbourne)', 'Swan (Pangbourne)', 'Swan (Pangbourne)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 151, 'Three Frogs (Wokingham)', 'Three Frogs (Wokingham)', 'Three Frogs (Wokingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 152, 'Two Poplars (Wokingham)', 'Two Poplars (Wokingham)', 'Two Poplars (Wokingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 153, 'White Horse (Abingdon)', 'White Horse (Abingdon)', 'White Horse (Abingdon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 154, 'White Swan (Sandhurst)', 'White Swan (Sandhurst)', 'White Swan (Sandhurst)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 155, 'Duchess (Colchester)', 'Duchess (Colchester)', 'Duchess (Colchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 156, 'Wig And Pen (Oxford)', 'Wig And Pen (Oxford)', 'Wig And Pen (Oxford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 157, 'Bystander, Wootton', 'Bystander, Wootton', 'Bystander, Wootton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 158, 'Tide End Cottage (Teddington)', 'Tide End Cottage (Teddington)', 'Tide End Cottage (Teddington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 159, 'Bald Faced Stag (East Finchley)', 'Bald Faced Stag (East Finchley)', 'Bald Faced Stag (East Finchley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 160, 'Crabtree (Fulham)', 'Crabtree (Fulham)', 'Crabtree (Fulham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 161, 'Duke Of Sussex (Chiswick)', 'Duke Of Sussex (Chiswick)', 'Duke Of Sussex (Chiswick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 162, 'Masons Arms (Kensal Green)', 'Masons Arms (Kensal Green)', 'Masons Arms (Kensal Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 163, 'Mitre (Holland Park)', 'Mitre (Holland Park)', 'Mitre (Holland Park)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 164, 'North London Tavern (Kilburn)', 'North London Tavern (Kilburn)', 'North London Tavern (Kilburn)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 165, 'Old Dairy (Finsbury Park)', 'Old Dairy (Finsbury Park)', 'Old Dairy (Finsbury Park)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 166, 'Pembroke (Earls Court)', 'Pembroke (Earls Court)', 'Pembroke (Earls Court)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 167, 'Prince Bonaparte (Paddington)', 'Prince Bonaparte (Paddington)', 'Prince Bonaparte (Paddington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 168, 'Queen Adelaide (Shepherds Bush)', 'Queen Adelaide (Shepherds Bush)', 'Queen Adelaide (Shepherds Bush)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 169, 'Vine (Kentish Town)', 'Vine (Kentish Town)', 'Vine (Kentish Town)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 170, 'Actress (East Dulwich)', 'Actress (East Dulwich)', 'Actress (East Dulwich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 171, 'Alexandra (Clapham)', 'Alexandra (Clapham)', 'Alexandra (Clapham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 172, 'Anglesea Arms (Sth Kensingtn)', 'Anglesea Arms (Sth Kensingtn)', 'Anglesea Arms (Sth Kensingtn)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 173, 'Black Swan (Ockham)', 'Black Swan (Ockham)', 'Black Swan (Ockham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 174, 'Boaters (Kingston-U-Thames)', 'Boaters (Kingston-U-Thames)', 'Boaters (Kingston-U-Thames)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 175, 'Durell Arms (Fulham)', 'Durell Arms (Fulham)', 'Durell Arms (Fulham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 176, 'Florence (Brixton)', 'Florence (Brixton)', 'Florence (Brixton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 177, 'George (Holborn)', 'George (Holborn)', 'George (Holborn)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 178, 'Golden Lion (St James)', 'Golden Lion (St James)', 'Golden Lion (St James)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 179, 'Havelock Tavern (Brook Green)', 'Havelock Tavern (Brook Green)', 'Havelock Tavern (Brook Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 180, 'Hemingford Arms (Islington)', 'Hemingford Arms (Islington)', 'Hemingford Arms (Islington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 181, 'Kew Gardens Hotel (Richmond)', 'Kew Gardens Hotel (Richmond)', 'Kew Gardens Hotel (Richmond)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 182, 'Ladbroke Arms (Kensington)', 'Ladbroke Arms (Kensington)', 'Ladbroke Arms (Kensington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 183, 'Paxton (West Dulwich)', 'Paxton (West Dulwich)', 'Paxton (West Dulwich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 184, 'Merchant (Clapham Junction)', 'Merchant (Clapham Junction)', 'Merchant (Clapham Junction)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 185, 'Morgan Arms (Bow)', 'Morgan Arms (Bow)', 'Morgan Arms (Bow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 186, 'New Cross House (New Cross)', 'New Cross House (New Cross)', 'New Cross House (New Cross)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 187, 'Artisan (Clerkenwell)', 'Artisan (Clerkenwell)', 'Artisan (Clerkenwell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 188, 'Rye (Peckham)', 'Rye (Peckham)', 'Rye (Peckham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 189, 'Square Pig (Holborn)', 'Square Pig (Holborn)', 'Square Pig (Holborn)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 190, 'Teddington Arms (Teddington)', 'Teddington Arms (Teddington)', 'Teddington Arms (Teddington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 191, 'Victoria Inn (Peckham)', 'Victoria Inn (Peckham)', 'Victoria Inn (Peckham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 192, 'Wandle (Earlsfield)', 'Wandle (Earlsfield)', 'Wandle (Earlsfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 193, 'Warwick Castle (Maida Vale)', 'Warwick Castle (Maida Vale)', 'Warwick Castle (Maida Vale)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 194, 'Worlds End (Finsbury Park)', 'Worlds End (Finsbury Park)', 'Worlds End (Finsbury Park)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 195, 'Island (Kensal Green)', 'Island (Kensal Green)', 'Island (Kensal Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 196, 'Old Engine House (Torquay)', 'Old Engine House (Torquay)', 'Old Engine House (Torquay)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 197, 'Carpenters Arms (Hayes)', 'Carpenters Arms (Hayes)', 'Carpenters Arms (Hayes)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 198, 'Black Horse (Trowbridge)', 'Black Horse (Trowbridge)', 'Black Horse (Trowbridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 199, 'Assembley House (Kentish Town)', 'Assembley House (Kentish Town)', 'Assembley House (Kentish Town)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 200, 'Windmill (Upminster)', 'Windmill (Upminster)', 'Windmill (Upminster)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 201, 'Butterchurn (Sutton)', 'Butterchurn (Sutton)', 'Butterchurn (Sutton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 202, 'Royal Oak (Marlborough)', 'Royal Oak (Marlborough)', 'Royal Oak (Marlborough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 203, 'Black Lion (West Hampstead)', 'Black Lion (West Hampstead)', 'Black Lion (West Hampstead)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 204, 'Bear & Ragged Staff (Crayford)', 'Bear & Ragged Staff (Crayford)', 'Bear & Ragged Staff (Crayford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 205, 'Brockley Jack (London Se4)', 'Brockley Jack (London Se4)', 'Brockley Jack (London Se4)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 206, 'Rose & Thistle (Reading)', 'Rose & Thistle (Reading)', 'Rose & Thistle (Reading)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 207, 'Vintners Parrot (Worthing)', 'Vintners Parrot (Worthing)', 'Vintners Parrot (Worthing)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 208, 'White Horse (Reading)', 'White Horse (Reading)', 'White Horse (Reading)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 209, 'Wackum Inn (Bristol)', 'Wackum Inn (Bristol)', 'Wackum Inn (Bristol)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 210, 'Star, Chalton', 'Star, Chalton', 'Star, Chalton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 211, 'Air Balloon (Horley)', 'Air Balloon (Horley)', 'Air Balloon (Horley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 212, 'Ashby Lodge, Scunthorpe', 'Ashby Lodge, Scunthorpe', 'Ashby Lodge, Scunthorpe', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 213, 'Barlow Croft (East Didsbury)', 'Barlow Croft (East Didsbury)', 'Barlow Croft (East Didsbury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 214, 'Beach, Littleborough', 'Beach, Littleborough', 'Beach, Littleborough', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 215, 'Bee Hive (Horwich)', 'Bee Hive (Horwich)', 'Bee Hive (Horwich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 216, 'Billing Mill (Little Billing)', 'Billing Mill (Little Billing)', 'Billing Mill (Little Billing)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 217, 'Bridgewater (Worsley)', 'Bridgewater (Worsley)', 'Bridgewater (Worsley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 218, 'Broadway (Short Heath)', 'Broadway (Short Heath)', 'Broadway (Short Heath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 219, 'Chesterfield Arms (Bretby)', 'Chesterfield Arms (Bretby)', 'Chesterfield Arms (Bretby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 220, 'Cock Inn, Rochford', 'Cock Inn, Rochford', 'Cock Inn, Rochford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 221, 'Dick Turpin, Wickford', 'Dick Turpin, Wickford', 'Dick Turpin, Wickford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 222, 'Fairway, Ruislip', 'Fairway, Ruislip', 'Fairway, Ruislip', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 223, 'Forest Inn (Holt Pound)', 'Forest Inn (Holt Pound)', 'Forest Inn (Holt Pound)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 224, 'Fradley Arms Hotel, Lichfield', 'Fradley Arms Hotel, Lichfield', 'Fradley Arms Hotel, Lichfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 225, 'Gatehouse (Clayton)', 'Gatehouse (Clayton)', 'Gatehouse (Clayton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 226, 'Gildersome Arms, Morley', 'Gildersome Arms, Morley', 'Gildersome Arms, Morley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 227, 'Gingerbread Man, Market Drayton', 'Gingerbread Man, Market Drayton', 'Gingerbread Man, Market Drayton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 228, 'Grapes Hotel (Portico)', 'Grapes Hotel (Portico)', 'Grapes Hotel (Portico)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 229, 'Half Moon (Whitwell Common)', 'Half Moon (Whitwell Common)', 'Half Moon (Whitwell Common)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 230, 'Hare & Hounds (Menston)', 'Hare & Hounds (Menston)', 'Hare & Hounds (Menston)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 231, 'Hartford Mill, Huntingdon', 'Hartford Mill, Huntingdon', 'Hartford Mill, Huntingdon', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 232, 'Harvest Mouse (Heswall)', 'Harvest Mouse (Heswall)', 'Harvest Mouse (Heswall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 233, 'Heath Farm, Congleton', 'Heath Farm, Congleton', 'Heath Farm, Congleton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 234, 'Star (Burnley)', 'Star (Burnley)', 'Star (Burnley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 235, 'Horse & Jockey, Inkford', 'Horse & Jockey, Inkford', 'Horse & Jockey, Inkford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 236, 'Longshoot, Nuneaton', 'Longshoot, Nuneaton', 'Longshoot, Nuneaton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 237, 'Lord Ted, Newark', 'Lord Ted, Newark', 'Lord Ted, Newark', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 238, 'Marquis (Low Stubbin)', 'Marquis (Low Stubbin)', 'Marquis (Low Stubbin)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 239, 'Merry Go Round, Hartlepool', 'Merry Go Round, Hartlepool', 'Merry Go Round, Hartlepool', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 240, 'Mill House (Emersons Green)', 'Mill House (Emersons Green)', 'Mill House (Emersons Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 241, 'Mill House (Chippenham)', 'Mill House (Chippenham)', 'Mill House (Chippenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 242, 'Moorings, Boothstown Worsley', 'Moorings, Boothstown Worsley', 'Moorings, Boothstown Worsley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 243, 'Mottram Wood (Mottram)', 'Mottram Wood (Mottram)', 'Mottram Wood (Mottram)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 244, 'Myllet Arms (Greenford)', 'Myllet Arms (Greenford)', 'Myllet Arms (Greenford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 245, 'New Florence (Longton)', 'New Florence (Longton)', 'New Florence (Longton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 246, 'New Tardebigge (Tardebigge)', 'New Tardebigge (Tardebigge)', 'New Tardebigge (Tardebigge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 247, 'Nickelodeon (Wednesfield)', 'Nickelodeon (Wednesfield)', 'Nickelodeon (Wednesfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 248, 'Old Cobblers Inn (Rawtenstall)', 'Old Cobblers Inn (Rawtenstall)', 'Old Cobblers Inn (Rawtenstall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 249, 'Old House At Home, Harborne', 'Old House At Home, Harborne', 'Old House At Home, Harborne', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 250, 'Old Rectory, Leybourne', 'Old Rectory, Leybourne', 'Old Rectory, Leybourne', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 251, 'Overstone Manor (Sywell)', 'Overstone Manor (Sywell)', 'Overstone Manor (Sywell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 252, 'Peacock Lodge (Newchapel)', 'Peacock Lodge (Newchapel)', 'Peacock Lodge (Newchapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 253, 'Plough Inn, Alsager', 'Plough Inn, Alsager', 'Plough Inn, Alsager', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 254, 'Pub On The Pond, Swansea', 'Pub On The Pond, Swansea', 'Pub On The Pond, Swansea', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 255, 'Quantock, Bridgwater', 'Quantock, Bridgwater', 'Quantock, Bridgwater', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 256, 'Quays - Billing, Billing', 'Quays - Billing, Billing', 'Quays - Billing, Billing', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 257, 'Cock & Bell (Long Melford)', 'Cock & Bell (Long Melford)', 'Cock & Bell (Long Melford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 258, 'Waterfront Inn (Diss)', 'Waterfront Inn (Diss)', 'Waterfront Inn (Diss)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 259, 'Red Robin, Wigan', 'Red Robin, Wigan', 'Red Robin, Wigan', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 260, 'Rising Sun (Gawsworth)', 'Rising Sun (Gawsworth)', 'Rising Sun (Gawsworth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 261, 'Highwayman (Graveley)', 'Highwayman (Graveley)', 'Highwayman (Graveley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 262, 'Jude The Obscure (Oxford)', 'Jude The Obscure (Oxford)', 'Jude The Obscure (Oxford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 263, 'Merlin (Swindon)', 'Merlin (Swindon)', 'Merlin (Swindon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 264, 'Prince Of Wales (Didcot)', 'Prince Of Wales (Didcot)', 'Prince Of Wales (Didcot)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 265, 'Royal Standard (Headington)', 'Royal Standard (Headington)', 'Royal Standard (Headington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 266, 'White Horse (Bicester)', 'White Horse (Bicester)', 'White Horse (Bicester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 267, 'Sir Jack (Bramley)', 'Sir Jack (Bramley)', 'Sir Jack (Bramley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 268, 'Smithy Pond (Wingerworth)', 'Smithy Pond (Wingerworth)', 'Smithy Pond (Wingerworth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 269, 'Squinting Cat (Lund House Green)', 'Squinting Cat (Lund House Green)', 'Squinting Cat (Lund House Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 270, 'Squire Yorke, Wrexham', 'Squire Yorke, Wrexham', 'Squire Yorke, Wrexham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 271, 'Star, Congresbury', 'Star, Congresbury', 'Star, Congresbury', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 272, 'Station Promenade, Morecambe', 'Station Promenade, Morecambe', 'Station Promenade, Morecambe', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 273, 'Story Book (Boldon)', 'Story Book (Boldon)', 'Story Book (Boldon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 274, 'Story Teller', 'Story Teller', 'Story Teller', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 275, 'Swiss Cottage, Shoreham by Sea', 'Swiss Cottage, Shoreham by Sea', 'Swiss Cottage, Shoreham by Sea', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 276, 'Tap & Railway (West Moors)', 'Tap & Railway (West Moors)', 'Tap & Railway (West Moors)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 277, 'Thatched House (Milton Locks)', 'Thatched House (Milton Locks)', 'Thatched House (Milton Locks)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 278, 'Waggon & Horses (Handforth)', 'Waggon & Horses (Handforth)', 'Waggon & Horses (Handforth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 279, 'Wilmington Arms (Clerkenwell)', 'Wilmington Arms (Clerkenwell)', 'Wilmington Arms (Clerkenwell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 280, 'Wheatsheaf (Dunham-On-The-Hill)', 'Wheatsheaf (Dunham-On-The-Hill)', 'Wheatsheaf (Dunham-On-The-Hill)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 281, 'White Horse, Shrewsbury', 'White Horse, Shrewsbury', 'White Horse, Shrewsbury', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 282, 'Wishing Well (Kingswood)', 'Wishing Well (Kingswood)', 'Wishing Well (Kingswood)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 283, 'Beggars Bush (Kingstanding)', 'Beggars Bush (Kingstanding)', 'Beggars Bush (Kingstanding)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 284, 'Black Bull (Benton)', 'Black Bull (Benton)', 'Black Bull (Benton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 285, 'Lucas Arms (London)', 'Lucas Arms (London)', 'Lucas Arms (London)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 286, 'Clocktower, Milton Keynes', 'Clocktower, Milton Keynes', 'Clocktower, Milton Keynes', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 287, 'Generous Pioneer, Ilkley', 'Generous Pioneer, Ilkley', 'Generous Pioneer, Ilkley', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 288, 'Melrose Inn, Cardiff', 'Melrose Inn, Cardiff', 'Melrose Inn, Cardiff', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 289, 'Maynard Arms (Crouch End)', 'Maynard Arms (Crouch End)', 'Maynard Arms (Crouch End)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 290, 'Ring O Bells, Loughborough', 'Ring O Bells, Loughborough', 'Ring O Bells, Loughborough', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 291, 'Rose & Crown, Coventry', 'Rose & Crown, Coventry', 'Rose & Crown, Coventry', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 292, 'Rugby Tavern (Cubbington)', 'Rugby Tavern (Cubbington)', 'Rugby Tavern (Cubbington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 293, 'Sneyd Arms (Sneyd Green)', 'Sneyd Arms (Sneyd Green)', 'Sneyd Arms (Sneyd Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 294, 'Woodman Inn (Codsall)', 'Woodman Inn (Codsall)', 'Woodman Inn (Codsall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 295, 'Admiral Rodney', 'Admiral Rodney', 'Admiral Rodney', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 296, 'Bears Paw', 'Bears Paw', 'Bears Paw', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 297, 'Bell', 'Bell', 'Bell', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 298, 'Black Prince', 'Black Prince', 'Black Prince', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 299, 'Boat House', 'Boat House', 'Boat House', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 300, 'Burrell Arms', 'Burrell Arms', 'Burrell Arms', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 301, 'Channings Hotel', 'Channings Hotel', 'Channings Hotel', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 302, 'Charlton Arms', 'Charlton Arms', 'Charlton Arms', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 303, 'Church View Inn', 'Church View Inn', 'Church View Inn', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 304, 'Dog & Gun', 'Dog & Gun', 'Dog & Gun', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 305, 'Dunes Hotel', 'Dunes Hotel', 'Dunes Hotel', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 306, 'Earl Beatty', 'Earl Beatty', 'Earl Beatty', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 307, 'Fiveways', 'Fiveways', 'Fiveways', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 308, 'Flying Saucer', 'Flying Saucer', 'Flying Saucer', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 309, 'Golden Fleece, Lymm', 'Golden Fleece, Lymm', 'Golden Fleece, Lymm', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 310, 'Good Companions', 'Good Companions', 'Good Companions', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 311, 'Green Man, Bedfont', 'Green Man, Bedfont', 'Green Man, Bedfont', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 312, 'Hare & Hounds, Ramsbottom, Bury', 'Hare & Hounds, Ramsbottom, Bury', 'Hare & Hounds, Ramsbottom, Bury', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 313, 'Horse & Groom (Streatham)', 'Horse & Groom (Streatham)', 'Horse & Groom (Streatham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 314, 'Hoy & Helmet, Benfleet', 'Hoy & Helmet, Benfleet', 'Hoy & Helmet, Benfleet', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 315, 'Inn on the Green', 'Inn on the Green', 'Inn on the Green', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 316, 'Kings Head Hotel', 'Kings Head Hotel', 'Kings Head Hotel', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 317, 'Larkshall', 'Larkshall', 'Larkshall', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 318, 'Malt Shovel (Baildon)', 'Malt Shovel (Baildon)', 'Malt Shovel (Baildon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 319, 'Marquis Of Granby', 'Marquis Of Granby', 'Marquis Of Granby', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 320, 'Old Club House', 'Old Club House', 'Old Club House', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 321, 'Old Rooms Inn', 'Old Rooms Inn', 'Old Rooms Inn', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 322, 'Paul Pry', 'Paul Pry', 'Paul Pry', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 323, 'Rockingham Arms (Wentworth)', 'Rockingham Arms (Wentworth)', 'Rockingham Arms (Wentworth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 324, 'Rose Inn', 'Rose Inn', 'Rose Inn', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 325, 'Snooty Fox (Three Bridges)', 'Snooty Fox (Three Bridges)', 'Snooty Fox (Three Bridges)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 326, 'Spanish Lady', 'Spanish Lady', 'Spanish Lady', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 327, 'Spyglass & Kettle', 'Spyglass & Kettle', 'Spyglass & Kettle', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 328, 'Thatched Cottage, Maidenhead', 'Thatched Cottage, Maidenhead', 'Thatched Cottage, Maidenhead', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 329, 'Three Magpies, Heathrow', 'Three Magpies, Heathrow', 'Three Magpies, Heathrow', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 330, 'Victory Inn', 'Victory Inn', 'Victory Inn', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 331, 'Wentworth Arms (Elmesthorpe)', 'Wentworth Arms (Elmesthorpe)', 'Wentworth Arms (Elmesthorpe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 332, 'Wharf Tavern', 'Wharf Tavern', 'Wharf Tavern', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 333, 'White Hart (cheadle)', 'White Hart (cheadle)', 'White Hart (cheadle)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 334, 'White Lion (Frenchay)', 'White Lion (Frenchay)', 'White Lion (Frenchay)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 335, 'Airman, Feltham', 'Airman, Feltham', 'Airman, Feltham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 336, 'Anchor & Horseshoes, Guildford', 'Anchor & Horseshoes, Guildford', 'Anchor & Horseshoes, Guildford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 337, 'Angel (Baildon)', 'Angel (Baildon)', 'Angel (Baildon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 338, 'Arrow (Arnold)', 'Arrow (Arnold)', 'Arrow (Arnold)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 339, 'Beehive (Carlisle)', 'Beehive (Carlisle)', 'Beehive (Carlisle)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 340, 'Bull & Chequers, Reading', 'Bull & Chequers, Reading', 'Bull & Chequers, Reading', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 341, 'County (Gosforth)', 'County (Gosforth)', 'County (Gosforth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 342, 'Crown, Bradford', 'Crown, Bradford', 'Crown, Bradford', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 343, 'Dog & Partridge, Blackpool', 'Dog & Partridge, Blackpool', 'Dog & Partridge, Blackpool', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 344, 'Farmers Arms (Northenden)', 'Farmers Arms (Northenden)', 'Farmers Arms (Northenden)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 345, 'Gardeners Arms, Stockport', 'Gardeners Arms, Stockport', 'Gardeners Arms, Stockport', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 346, 'George & Dragon Hotel, Stockport', 'George & Dragon Hotel, Stockport', 'George & Dragon Hotel, Stockport', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 347, 'Golden Eagle, Carterton', 'Golden Eagle, Carterton', 'Golden Eagle, Carterton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 348, 'Golf Hotel (Rushmere)', 'Golf Hotel (Rushmere)', 'Golf Hotel (Rushmere)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 349, 'Griffin (Warmley)', 'Griffin (Warmley)', 'Griffin (Warmley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 350, 'Gunner, North Shields', 'Gunner, North Shields', 'Gunner, North Shields', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 351, 'Harvey, Swindon', 'Harvey, Swindon', 'Harvey, Swindon', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 352, 'Jolly Fenman, Sidcup', 'Jolly Fenman, Sidcup', 'Jolly Fenman, Sidcup', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 353, 'Longship, Hebburn', 'Longship, Hebburn', 'Longship, Hebburn', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 354, 'Marine, Hornsea', 'Marine, Hornsea', 'Marine, Hornsea', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 355, 'Morden Brook, Morden', 'Morden Brook, Morden', 'Morden Brook, Morden', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 356, 'Noak Bridge (Laindon)', 'Noak Bridge (Laindon)', 'Noak Bridge (Laindon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 357, 'Oak Tree, Mansfield', 'Oak Tree, Mansfield', 'Oak Tree, Mansfield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 358, 'Pear & Partridge (Perton)', 'Pear & Partridge (Perton)', 'Pear & Partridge (Perton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 359, 'Prince of Wales, Norwich', 'Prince of Wales, Norwich', 'Prince of Wales, Norwich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 360, 'Red Lion Inn, Sheffield', 'Red Lion Inn, Sheffield', 'Red Lion Inn, Sheffield', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 361, 'Royal , Scunthorpe', 'Royal , Scunthorpe', 'Royal , Scunthorpe', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 362, 'Soldiers Return (Ickenham)', 'Soldiers Return (Ickenham)', 'Soldiers Return (Ickenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 363, 'Station, Stoneleigh', 'Station, Stoneleigh', 'Station, Stoneleigh', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 364, 'Station Hotel (Crossgates)', 'Station Hotel (Crossgates)', 'Station Hotel (Crossgates)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 365, 'Tap & Tumbler, Nottingham', 'Tap & Tumbler, Nottingham', 'Tap & Tumbler, Nottingham', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 366, 'Thatched Cottage (Cove)', 'Thatched Cottage (Cove)', 'Thatched Cottage (Cove)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 367, 'Turks Head (Tynemouth)', 'Turks Head (Tynemouth)', 'Turks Head (Tynemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 368, 'White Elephant, Northampton', 'White Elephant, Northampton', 'White Elephant, Northampton', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 369, 'Windmill Inn (Werrington)', 'Windmill Inn (Werrington)', 'Windmill Inn (Werrington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 370, 'Woolpack, Norwich', 'Woolpack, Norwich', 'Woolpack, Norwich', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 371, 'Ye Olde Black Horse (Lamorbey)', 'Ye Olde Black Horse (Lamorbey)', 'Ye Olde Black Horse (Lamorbey)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 372, 'Zach Willsher, Benfleet', 'Zach Willsher, Benfleet', 'Zach Willsher, Benfleet', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 373, 'William Garland (Caterham)', 'William Garland (Caterham)', 'William Garland (Caterham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 374, 'Regent (Chapel Allerton)', 'Regent (Chapel Allerton)', 'Regent (Chapel Allerton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 375, 'Spinney Hill', 'Spinney Hill', 'Spinney Hill', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 376, 'Windmill Inn, York', 'Windmill Inn, York', 'Windmill Inn, York', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 377, 'George (Belsize Park)', 'George (Belsize Park)', 'George (Belsize Park)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 378, 'Lullingstone Castle (Swanley)', 'Lullingstone Castle (Swanley)', 'Lullingstone Castle (Swanley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 379, 'Abington (Northampton)', 'Abington (Northampton)', 'Abington (Northampton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 380, 'Ainsty (York)', 'Ainsty (York)', 'Ainsty (York)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 381, 'Albert Tavern (South Norwood)', 'Albert Tavern (South Norwood)', 'Albert Tavern (South Norwood)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 382, 'Crab Apple (Clevedon)', 'Crab Apple (Clevedon)', 'Crab Apple (Clevedon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 383, 'Mitre (Southampton)', 'Mitre (Southampton)', 'Mitre (Southampton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 384, 'Acorn (Burncross)', 'Acorn (Burncross)', 'Acorn (Burncross)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 385, 'Anchor (Cambridge)', 'Anchor (Cambridge)', 'Anchor (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 386, 'Ancient Foresters (Wibsey)', 'Ancient Foresters (Wibsey)', 'Ancient Foresters (Wibsey)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 387, 'Arkles (Liverpool)', 'Arkles (Liverpool)', 'Arkles (Liverpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 388, 'Baffins (Portsmouth)', 'Baffins (Portsmouth)', 'Baffins (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 389, 'Ball (Sheffield)', 'Ball (Sheffield)', 'Ball (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 390, 'Bamburgh (South Shields)', 'Bamburgh (South Shields)', 'Bamburgh (South Shields)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 391, 'Bath House (Cambridge)', 'Bath House (Cambridge)', 'Bath House (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 392, 'Beaconsfield (Gateshead)', 'Beaconsfield (Gateshead)', 'Beaconsfield (Gateshead)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 393, 'Bear & Ragged Staff (Kenilwor)', 'Bear & Ragged Staff (Kenilwor)', 'Bear & Ragged Staff (Kenilwor)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 394, 'Bell (Shottery)', 'Bell (Shottery)', 'Bell (Shottery)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 395, 'Ben Lomond (Jarrow)', 'Ben Lomond (Jarrow)', 'Ben Lomond (Jarrow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 396, 'Big Tree (Sheffield)', 'Big Tree (Sheffield)', 'Big Tree (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 397, 'Billet (Sittingbourne)', 'Billet (Sittingbourne)', 'Billet (Sittingbourne)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 398, 'Bird In Hand (Beck Row)', 'Bird In Hand (Beck Row)', 'Bird In Hand (Beck Row)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 399, 'Birkey (Liverpool)', 'Birkey (Liverpool)', 'Birkey (Liverpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 400, 'Black Horse (Walton)', 'Black Horse (Walton)', 'Black Horse (Walton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 401, 'Black Horse (Old Swan)', 'Black Horse (Old Swan)', 'Black Horse (Old Swan)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 402, 'Black Horse (Exeter)', 'Black Horse (Exeter)', 'Black Horse (Exeter)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 403, 'Blackbirds (Flitwick)', 'Blackbirds (Flitwick)', 'Blackbirds (Flitwick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 404, 'Blue Posts (Mayfair)', 'Blue Posts (Mayfair)', 'Blue Posts (Mayfair)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 405, 'Bold Forester (Southsea)', 'Bold Forester (Southsea)', 'Bold Forester (Southsea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 406, 'Brewmaster (St James's)', 'Brewmaster (St James's)', 'Brewmaster (St James's)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 407, 'Bridge (Bracknell)', 'Bridge (Bracknell)', 'Bridge (Bracknell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 408, 'Broadwater (Worthing)', 'Broadwater (Worthing)', 'Broadwater (Worthing)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 409, 'Broadway (Bournemouth)', 'Broadway (Bournemouth)', 'Broadway (Bournemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 410, 'Bromborough (Wirral)', 'Bromborough (Wirral)', 'Bromborough (Wirral)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 411, 'Brunswick (Bournemouth)', 'Brunswick (Bournemouth)', 'Brunswick (Bournemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 412, 'Buff (Orpington)', 'Buff (Orpington)', 'Buff (Orpington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 413, 'Bull (Penenden Heath)', 'Bull (Penenden Heath)', 'Bull (Penenden Heath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 414, 'Speckled Hen (St Albans)', 'Speckled Hen (St Albans)', 'Speckled Hen (St Albans)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 415, 'Caernarvon Castle (Prenton)', 'Caernarvon Castle (Prenton)', 'Caernarvon Castle (Prenton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 416, 'Carleton (Pontefract)', 'Carleton (Pontefract)', 'Carleton (Pontefract)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 417, 'Castle In The Air (Fareham)', 'Castle In The Air (Fareham)', 'Castle In The Air (Fareham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 418, 'Red Cat (Greasby)', 'Red Cat (Greasby)', 'Red Cat (Greasby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 419, 'Chequers (Bromley)', 'Chequers (Bromley)', 'Chequers (Bromley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 420, 'Chestnut Tree (Andover)', 'Chestnut Tree (Andover)', 'Chestnut Tree (Andover)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 421, 'City Of Quebec (Marylebone)', 'City Of Quebec (Marylebone)', 'City Of Quebec (Marylebone)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 422, 'Clarence Garden (Portsmouth)', 'Clarence Garden (Portsmouth)', 'Clarence Garden (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 423, 'Claude (Cardiff)', 'Claude (Cardiff)', 'Claude (Cardiff)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 424, 'Clive Arms (Cardiff)', 'Clive Arms (Cardiff)', 'Clive Arms (Cardiff)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 425, 'Coach & Horses (Soho)', 'Coach & Horses (Soho)', 'Coach & Horses (Soho)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 426, 'Coach & Horses (Wimborne)', 'Coach & Horses (Wimborne)', 'Coach & Horses (Wimborne)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 427, 'Commercial (Killay)', 'Commercial (Killay)', 'Commercial (Killay)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 428, 'Compasses (Tunbridge Wells)', 'Compasses (Tunbridge Wells)', 'Compasses (Tunbridge Wells)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 429, 'Coopers (Bretton)', 'Coopers (Bretton)', 'Coopers (Bretton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 430, 'Coopers Mill (Yeovil)', 'Coopers Mill (Yeovil)', 'Coopers Mill (Yeovil)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 431, 'Coronation (Southport)', 'Coronation (Southport)', 'Coronation (Southport)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 432, 'Crane (Basildon)', 'Crane (Basildon)', 'Crane (Basildon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 433, 'Town House (Lytham St Annes)', 'Town House (Lytham St Annes)', 'Town House (Lytham St Annes)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 434, 'Cricketers (Southwick)', 'Cricketers (Southwick)', 'Cricketers (Southwick)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 435, 'Cricketers Arms (Chandlers Ford)', 'Cricketers Arms (Chandlers Ford)', 'Cricketers Arms (Chandlers Ford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 436, 'Crown (Horsham)', 'Crown (Horsham)', 'Crown (Horsham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 437, 'Crown & Horseshoes (Enfield)', 'Crown & Horseshoes (Enfield)', 'Crown & Horseshoes (Enfield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 438, 'Crown Wood (Bracknell)', 'Crown Wood (Bracknell)', 'Crown Wood (Bracknell)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 439, 'Cuckoo Pint (Fareham)', 'Cuckoo Pint (Fareham)', 'Cuckoo Pint (Fareham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 440, 'Devon (Leeds)', 'Devon (Leeds)', 'Devon (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 441, 'Devonshire Arms (Sheffield)', 'Devonshire Arms (Sheffield)', 'Devonshire Arms (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 442, 'Dog & Partridge (Morecambe)', 'Dog & Partridge (Morecambe)', 'Dog & Partridge (Morecambe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 443, 'Dragon (Leeds)', 'Dragon (Leeds)', 'Dragon (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 444, 'Druids Arms (Maidstone)', 'Druids Arms (Maidstone)', 'Druids Arms (Maidstone)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 445, 'Druids Head (Kingston-U-Thame)', 'Druids Head (Kingston-U-Thame)', 'Druids Head (Kingston-U-Thame)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 446, 'Eager Poet (Neath Hill)', 'Eager Poet (Neath Hill)', 'Eager Poet (Neath Hill)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 447, 'Earl Of Cornwall (Slough)', 'Earl Of Cornwall (Slough)', 'Earl Of Cornwall (Slough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 448, 'Endbutt (Liverpool)', 'Endbutt (Liverpool)', 'Endbutt (Liverpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 449, 'Ewe & Lamb (Dunstable)', 'Ewe & Lamb (Dunstable)', 'Ewe & Lamb (Dunstable)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 450, 'Victoria (Aldershot)', 'Victoria (Aldershot)', 'Victoria (Aldershot)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 451, 'Bakers (Basingstoke)', 'Bakers (Basingstoke)', 'Bakers (Basingstoke)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 452, 'Bishops Tavern (Bristol)', 'Bishops Tavern (Bristol)', 'Bishops Tavern (Bristol)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 453, 'Grain & Hop Store (Cambridge)', 'Grain & Hop Store (Cambridge)', 'Grain & Hop Store (Cambridge)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 454, 'Trents (Chichester)', 'Trents (Chichester)', 'Trents (Chichester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 455, 'Copper Pot (Leamington Spa)', 'Copper Pot (Leamington Spa)', 'Copper Pot (Leamington Spa)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 456, 'Monument (Whitechapel)', 'Monument (Whitechapel)', 'Monument (Whitechapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 457, 'Churchill (Poole)', 'Churchill (Poole)', 'Churchill (Poole)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 458, 'Guild (Preston)', 'Guild (Preston)', 'Guild (Preston)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 459, 'Outlook (Reading)', 'Outlook (Reading)', 'Outlook (Reading)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 460, 'Museum (Sheffield)', 'Museum (Sheffield)', 'Museum (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 461, 'Duke Of York (Surbiton)', 'Duke Of York (Surbiton)', 'Duke Of York (Surbiton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 462, 'Sutton Arms (Sutton)', 'Sutton Arms (Sutton)', 'Sutton Arms (Sutton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 463, 'Hand & Racquet (Wimbledon)', 'Hand & Racquet (Wimbledon)', 'Hand & Racquet (Wimbledon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 464, 'Lendal Cellars (York)', 'Lendal Cellars (York)', 'Lendal Cellars (York)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 465, 'Farmers Arms (Blackpool)', 'Farmers Arms (Blackpool)', 'Farmers Arms (Blackpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 466, 'Farmers Arms (Wirral)', 'Farmers Arms (Wirral)', 'Farmers Arms (Wirral)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 467, 'Festing (Southsea)', 'Festing (Southsea)', 'Festing (Southsea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 468, 'Flag (Egerton)', 'Flag (Egerton)', 'Flag (Egerton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 469, 'Bishop (East Dulwich)', 'Bishop (East Dulwich)', 'Bishop (East Dulwich)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 470, 'Monument (Hereford)', 'Monument (Hereford)', 'Monument (Hereford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 471, 'Freshfield (Liverpool)', 'Freshfield (Liverpool)', 'Freshfield (Liverpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 472, 'Frog & Parrot (Sheffield)', 'Frog & Parrot (Sheffield)', 'Frog & Parrot (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 473, 'Garrick Arms (Charing Cross)', 'Garrick Arms (Charing Cross)', 'Garrick Arms (Charing Cross)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 474, 'George (Southwark)', 'George (Southwark)', 'George (Southwark)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 475, 'George (Bexley)', 'George (Bexley)', 'George (Bexley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 476, 'George & Dragon (Chester)', 'George & Dragon (Chester)', 'George & Dragon (Chester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 477, 'George & Dragon (Hazel Grove)', 'George & Dragon (Hazel Grove)', 'George & Dragon (Hazel Grove)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 478, 'George & Dragon (Yiewsley)', 'George & Dragon (Yiewsley)', 'George & Dragon (Yiewsley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 479, 'George Abbot (Guildford)', 'George Abbot (Guildford)', 'George Abbot (Guildford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 480, 'Golden Hind (Portsmouth)', 'Golden Hind (Portsmouth)', 'Golden Hind (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 481, 'Golden Lion (Goring-By-Sea)', 'Golden Lion (Goring-By-Sea)', 'Golden Lion (Goring-By-Sea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 482, 'Good Companion (Portsmouth)', 'Good Companion (Portsmouth)', 'Good Companion (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 483, 'Green Posts (Portsmouth)', 'Green Posts (Portsmouth)', 'Green Posts (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 484, 'Black Griffin Inn (Lisvane)', 'Black Griffin Inn (Lisvane)', 'Black Griffin Inn (Lisvane)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 485, 'Guildford (Southend-0n-Sea)', 'Guildford (Southend-0n-Sea)', 'Guildford (Southend-0n-Sea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 486, 'Halfway Inn (Chandlers Ford)', 'Halfway Inn (Chandlers Ford)', 'Halfway Inn (Chandlers Ford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 487, 'Pippin (Maidstone)', 'Pippin (Maidstone)', 'Pippin (Maidstone)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 488, 'Hare & Billet (Blackheath)', 'Hare & Billet (Blackheath)', 'Hare & Billet (Blackheath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 489, 'Hare & Hounds (Gloucester)', 'Hare & Hounds (Gloucester)', 'Hare & Hounds (Gloucester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 490, 'Hatherley (Cheltenham)', 'Hatherley (Cheltenham)', 'Hatherley (Cheltenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 491, 'Hendon (Hendon)', 'Hendon (Hendon)', 'Hendon (Hendon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 492, 'Hop & Kilderkin (Bournemouth)', 'Hop & Kilderkin (Bournemouth)', 'Hop & Kilderkin (Bournemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 493, 'Horsforth (Horsforth)', 'Horsforth (Horsforth)', 'Horsforth (Horsforth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 494, 'Hungry Fox (Gillingham)', 'Hungry Fox (Gillingham)', 'Hungry Fox (Gillingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 495, 'Jingling Gate (Newcastle)', 'Jingling Gate (Newcastle)', 'Jingling Gate (Newcastle)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 496, 'Jolly Farmer (Winchester)', 'Jolly Farmer (Winchester)', 'Jolly Farmer (Winchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 497, 'Jolly Sailor (Poole)', 'Jolly Sailor (Poole)', 'Jolly Sailor (Poole)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 498, 'Kings Arms (Colchester)', 'Kings Arms (Colchester)', 'Kings Arms (Colchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 499, 'Kings Head (Slough)', 'Kings Head (Slough)', 'Kings Head (Slough)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 500, 'Kings Head (Upton St Leonards)', 'Kings Head (Upton St Leonards)', 'Kings Head (Upton St Leonards)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 501, 'Kings Stores (Whitechapel)', 'Kings Stores (Whitechapel)', 'Kings Stores (Whitechapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 502, 'Knowsley (Bury)', 'Knowsley (Bury)', 'Knowsley (Bury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 503, 'Lighthouse (Wallasey)', 'Lighthouse (Wallasey)', 'Lighthouse (Wallasey)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 504, 'Grove (Welwyn Garden City)', 'Grove (Welwyn Garden City)', 'Grove (Welwyn Garden City)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 505, 'Malt Shovel (Leeds)', 'Malt Shovel (Leeds)', 'Malt Shovel (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 506, 'Malt Shovel (Bridgwater)', 'Malt Shovel (Bridgwater)', 'Malt Shovel (Bridgwater)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 507, 'Ascott (Pinner)', 'Ascott (Pinner)', 'Ascott (Pinner)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 508, 'Manor House (Portsmouth)', 'Manor House (Portsmouth)', 'Manor House (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 509, 'Marlow Donkey (Marlow)', 'Marlow Donkey (Marlow)', 'Marlow Donkey (Marlow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 510, 'Masons Arms (Old Swan)', 'Masons Arms (Old Swan)', 'Masons Arms (Old Swan)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 511, 'Masons Arms (Wickersley)', 'Masons Arms (Wickersley)', 'Masons Arms (Wickersley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 512, 'Monks Brook (Chandlers Ford)', 'Monks Brook (Chandlers Ford)', 'Monks Brook (Chandlers Ford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 513, 'Mount Radford (Exeter)', 'Mount Radford (Exeter)', 'Mount Radford (Exeter)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 514, 'National Hunt (Cheltenham)', 'National Hunt (Cheltenham)', 'National Hunt (Cheltenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 515, 'New Derby (Sunderland)', 'New Derby (Sunderland)', 'New Derby (Sunderland)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 516, 'New Inn (Leeds)', 'New Inn (Leeds)', 'New Inn (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 517, 'New Moon (Whitechapel)', 'New Moon (Whitechapel)', 'New Moon (Whitechapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 518, 'Norwood Arms (Cheltenham)', 'Norwood Arms (Cheltenham)', 'Norwood Arms (Cheltenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 519, 'Old Five Bells (Burnham)', 'Old Five Bells (Burnham)', 'Old Five Bells (Burnham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 520, 'Nags Head (Welling)', 'Nags Head (Welling)', 'Nags Head (Welling)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 521, 'Old Star  (Westminster)', 'Old Star  (Westminster)', 'Old Star  (Westminster)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 522, 'Pavillion (Shepherds Bush)', 'Pavillion (Shepherds Bush)', 'Pavillion (Shepherds Bush)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 523, 'Penny Black (Sheffield)', 'Penny Black (Sheffield)', 'Penny Black (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 524, 'Copa (Cheltenham)', 'Copa (Cheltenham)', 'Copa (Cheltenham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 525, 'Pheasant (Birstall)', 'Pheasant (Birstall)', 'Pheasant (Birstall)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 526, 'Phoenix (Whitechapel)', 'Phoenix (Whitechapel)', 'Phoenix (Whitechapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 527, 'Pinner Arms (Pinner)', 'Pinner Arms (Pinner)', 'Pinner Arms (Pinner)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 528, 'Pond House (Maidenhead)', 'Pond House (Maidenhead)', 'Pond House (Maidenhead)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 529, 'Porter Brook (Sheffield)', 'Porter Brook (Sheffield)', 'Porter Brook (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 530, 'Portsbridge (Cosham)', 'Portsbridge (Cosham)', 'Portsbridge (Cosham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 531, 'Prince Albert (Brixton)', 'Prince Albert (Brixton)', 'Prince Albert (Brixton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 532, 'Prince Frederick (Bromley)', 'Prince Frederick (Bromley)', 'Prince Frederick (Bromley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 533, 'Priory (Scunthorpe)', 'Priory (Scunthorpe)', 'Priory (Scunthorpe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 534, 'Pump House (Liverpool)', 'Pump House (Liverpool)', 'Pump House (Liverpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 535, 'Queens Head (Chester-Le-Street', 'Queens Head (Chester-Le-Street', 'Queens Head (Chester-Le-Street', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 536, 'Railway (Burgess Hill)', 'Railway (Burgess Hill)', 'Railway (Burgess Hill)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 537, 'Railway (London Ec2)', 'Railway (London Ec2)', 'Railway (London Ec2)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 538, 'Railway (Burnham On Sea)', 'Railway (Burnham On Sea)', 'Railway (Burnham On Sea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 539, 'Red Lion (Skipton)', 'Red Lion (Skipton)', 'Red Lion (Skipton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 540, 'Red Lion (Darlington)', 'Red Lion (Darlington)', 'Red Lion (Darlington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 541, 'Red Lion (Portchester)', 'Red Lion (Portchester)', 'Red Lion (Portchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 542, 'Red Lion (Stubbington)', 'Red Lion (Stubbington)', 'Red Lion (Stubbington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 543, 'Red Lion (Wooburn Green)', 'Red Lion (Wooburn Green)', 'Red Lion (Wooburn Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 544, 'Red Rover (West Wellow)', 'Red Rover (West Wellow)', 'Red Rover (West Wellow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 545, 'Richmond Arms (Bournemouth)', 'Richmond Arms (Bournemouth)', 'Richmond Arms (Bournemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 546, 'Ring O Bells (West Kirby)', 'Ring O Bells (West Kirby)', 'Ring O Bells (West Kirby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 547, 'Rising Sun (Eltham)', 'Rising Sun (Eltham)', 'Rising Sun (Eltham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 548, 'Robin Hood (Tottington)', 'Robin Hood (Tottington)', 'Robin Hood (Tottington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 549, 'Romiley Arms (Romiley)', 'Romiley Arms (Romiley)', 'Romiley Arms (Romiley)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 550, 'Rose & Crown (Bury)', 'Rose & Crown (Bury)', 'Rose & Crown (Bury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 551, 'Rose & Crown (Hereford)', 'Rose & Crown (Hereford)', 'Rose & Crown (Hereford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 552, 'Rose & Crown (Woodford Green)', 'Rose & Crown (Woodford Green)', 'Rose & Crown (Woodford Green)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 553, 'Royal Oak (Winchester)', 'Royal Oak (Winchester)', 'Royal Oak (Winchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 554, 'Royal Oak (Charlton)', 'Royal Oak (Charlton)', 'Royal Oak (Charlton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 555, 'Royal Oak (Chorlton Cum Hardy)', 'Royal Oak (Chorlton Cum Hardy)', 'Royal Oak (Chorlton Cum Hardy)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 556, 'Rudds Arms (Marton-In-Clevela)', 'Rudds Arms (Marton-In-Clevela)', 'Rudds Arms (Marton-In-Clevela)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 557, 'Sandpiper (Christchurch)', 'Sandpiper (Christchurch)', 'Sandpiper (Christchurch)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 558, 'Sefton Arms (West Derby)', 'Sefton Arms (West Derby)', 'Sefton Arms (West Derby)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 559, 'Shakey (Sheffield)', 'Shakey (Sheffield)', 'Shakey (Sheffield)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 560, 'Sherlock Holmes (St James's)', 'Sherlock Holmes (St James's)', 'Sherlock Holmes (St James's)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 561, 'Ship (Exeter)', 'Ship (Exeter)', 'Ship (Exeter)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 562, 'Ship Anson (Portsmouth)', 'Ship Anson (Portsmouth)', 'Ship Anson (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 563, 'Silver Fern (Warsash)', 'Silver Fern (Warsash)', 'Silver Fern (Warsash)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 564, 'Skyrack (Leeds)', 'Skyrack (Leeds)', 'Skyrack (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 565, 'S Oak (Selly Oak)', 'S Oak (Selly Oak)', 'S Oak (Selly Oak)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 566, 'Salt Quay (Rotherhithe)', 'Salt Quay (Rotherhithe)', 'Salt Quay (Rotherhithe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 567, 'Spice Island (Portsmouth)', 'Spice Island (Portsmouth)', 'Spice Island (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 568, 'Gardeners (Chelmsford)', 'Gardeners (Chelmsford)', 'Gardeners (Chelmsford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 569, 'Spyglass & Kettle (Gillingham)', 'Spyglass & Kettle (Gillingham)', 'Spyglass & Kettle (Gillingham)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 570, 'Star (Haywards Heath)', 'Star (Haywards Heath)', 'Star (Haywards Heath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 571, 'Star & Garter (Portsmouth)', 'Star & Garter (Portsmouth)', 'Star & Garter (Portsmouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 572, 'Strawberry (Barrow-In-Furness)', 'Strawberry (Barrow-In-Furness)', 'Strawberry (Barrow-In-Furness)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 573, 'Swan (Brentwood)', 'Swan (Brentwood)', 'Swan (Brentwood)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 574, 'Taps (Lytham St Annes)', 'Taps (Lytham St Annes)', 'Taps (Lytham St Annes)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 575, 'Testwood (Totton)', 'Testwood (Totton)', 'Testwood (Totton)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 576, 'Three Elms (Hereford)', 'Three Elms (Hereford)', 'Three Elms (Hereford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 577, 'Travellers Rest (Leeds)', 'Travellers Rest (Leeds)', 'Travellers Rest (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 578, 'Tredegar Arms (Bassaleg)', 'Tredegar Arms (Bassaleg)', 'Tredegar Arms (Bassaleg)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 579, 'Turf Tavern (Oxford)', 'Turf Tavern (Oxford)', 'Turf Tavern (Oxford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 580, 'Tut N Shive (Doncaster)', 'Tut N Shive (Doncaster)', 'Tut N Shive (Doncaster)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 581, 'Two Brewers (Chepstow)', 'Two Brewers (Chepstow)', 'Two Brewers (Chepstow)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 582, 'Unicorn (Ilford)', 'Unicorn (Ilford)', 'Unicorn (Ilford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 583, 'Uplands Tavern (Uplands)', 'Uplands Tavern (Uplands)', 'Uplands Tavern (Uplands)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 584, 'Victoria (Barrow-In-Furness)', 'Victoria (Barrow-In-Furness)', 'Victoria (Barrow-In-Furness)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 585, 'Walkford (Walkford)', 'Walkford (Walkford)', 'Walkford (Walkford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 586, 'Washington (Blackpool)', 'Washington (Blackpool)', 'Washington (Blackpool)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 587, 'Waterside (Shoreham-By-Sea)', 'Waterside (Shoreham-By-Sea)', 'Waterside (Shoreham-By-Sea)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 588, 'Wellington (Bebington)', 'Wellington (Bebington)', 'Wellington (Bebington)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 589, 'Westbourne (Bournemouth)', 'Westbourne (Bournemouth)', 'Westbourne (Bournemouth)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 590, 'White Hart (Gosport)', 'White Hart (Gosport)', 'White Hart (Gosport)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 591, 'William Camden (Bexleyheath)', 'William Camden (Bexleyheath)', 'William Camden (Bexleyheath)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 592, 'Williams (Whitechapel)', 'Williams (Whitechapel)', 'Williams (Whitechapel)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 593, 'Windmill (Stratford-U-Avon)', 'Windmill (Stratford-U-Avon)', 'Windmill (Stratford-U-Avon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 594, 'Windmill (Freshbrook)', 'Windmill (Freshbrook)', 'Windmill (Freshbrook)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 595, 'Woodies (Leeds)', 'Woodies (Leeds)', 'Woodies (Leeds)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 596, 'Woodlands Edge (Sth Ockenden)', 'Woodlands Edge (Sth Ockenden)', 'Woodlands Edge (Sth Ockenden)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 597, 'Ye Olde Cock (Didsbury)', 'Ye Olde Cock (Didsbury)', 'Ye Olde Cock (Didsbury)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 598, 'Woodside (Crewe)', 'Woodside (Crewe)', 'Woodside (Crewe)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 599, 'Albion (Portishead)', 'Albion (Portishead)', 'Albion (Portishead)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 600, 'Anton Arms (Andover)', 'Anton Arms (Andover)', 'Anton Arms (Andover)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 601, 'Barleycorn (Hedge End)', 'Barleycorn (Hedge End)', 'Barleycorn (Hedge End)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 602, 'College Oak (Abingdon)', 'College Oak (Abingdon)', 'College Oak (Abingdon)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 603, 'County Arms (Winchester)', 'County Arms (Winchester)', 'County Arms (Winchester)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 604, 'Duke Of Monmouth (Oxford)', 'Duke Of Monmouth (Oxford)', 'Duke Of Monmouth (Oxford)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 605, 'Waterside, Rugby', 'Waterside, Rugby', 'Waterside, Rugby', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 606, 'Rose & Crown (Rushden)', 'Rose & Crown (Rushden)', 'Rose & Crown (Rushden)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 607, 'West End Brewery (West End)', 'West End Brewery (West End)', 'West End Brewery (West End)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 608, 'Welcome (Eastleigh)', 'Welcome (Eastleigh)', 'Welcome (Eastleigh)', NULL, 'belhaven', NULL),
(@SiteID, @Lang, @Device, 'group_100', 609, 'Footman (Mayfair)', 'Footman (Mayfair)', 'Footman (Mayfair)', NULL, 'belhaven', NULL),
